In [24]:
import numpy as np
from dotenv import load_dotenv
import pandas as pd
import os
import pandas as pd
from pathlib import Path
from IPython.display import display
from locale import atof
from openpyxl.styles import numbers
from datetime import datetime

BASE_DIR = Path('/Users/andresuchitra/dev/missglam/autopo/notebook')


# Configuration
SUPPLIER_PATH = BASE_DIR / 'data/supplier.csv'
RAWPO_DIR = BASE_DIR / 'data/rawpo/csv'
INPUT_DIR = BASE_DIR / 'data/input'
RAWPO_XLSX_DIR = BASE_DIR / 'data/rawpo/xlsx'
STORE_CONTRIBUTION_PATH = BASE_DIR / 'data/store_contribution.csv'

OUTPUT_BASE_DIR = BASE_DIR / 'output'
OUTPUT_DATE_DIR = None

OUTPUT_DIR = OUTPUT_BASE_DIR / 'complete'
OUTPUT_EXCEL_DIR = OUTPUT_BASE_DIR / 'excel'
OUTPUT_M2_DIR = OUTPUT_BASE_DIR / 'm2'
OUTPUT_EMERGENCY_DIR = OUTPUT_BASE_DIR / 'emergency'

TOP_100_SKU_DIR = BASE_DIR / 'data/top_100_sku'


def configure_output_dirs(run_date: str | None):
    global OUTPUT_DATE_DIR
    global OUTPUT_DIR, OUTPUT_EXCEL_DIR, OUTPUT_M2_DIR, OUTPUT_EMERGENCY_DIR

    if run_date is None or str(run_date).strip() == '':
        OUTPUT_DATE_DIR = None
        OUTPUT_DIR = OUTPUT_BASE_DIR / 'complete'
        OUTPUT_EXCEL_DIR = OUTPUT_BASE_DIR / 'excel'
        OUTPUT_M2_DIR = OUTPUT_BASE_DIR / 'm2'
        OUTPUT_EMERGENCY_DIR = OUTPUT_BASE_DIR / 'emergency'
        return

    date_str = str(run_date).strip()
    OUTPUT_DATE_DIR = OUTPUT_BASE_DIR / date_str

    OUTPUT_DIR = OUTPUT_DATE_DIR / 'complete'
    OUTPUT_EXCEL_DIR = OUTPUT_DATE_DIR / 'excel'
    OUTPUT_M2_DIR = OUTPUT_DATE_DIR / 'm2'
    OUTPUT_EMERGENCY_DIR = OUTPUT_DATE_DIR / 'emergency'


NUMERIC_COLUMNS = [
    'HPP', 'Harga', 'Ranking', 'Grade', 'Terjual', 'Stok', 'Lost Days',
    'Velocity Capped', 'Daily Sales', 'Lead Time', 'Max. Daily Sales',
    'Max. Lead Time', 'Min. Order', 'Safety Stok', 'ROP', '3W Cover',
    'Sedang PO', 'Suggested', 'Amount', 'Promo Factor', 'Delay Factor',
    'Stock Cover', 'Days to Backup', 'Qty to Backup'
]

NA_VALUES = {
    'NAN', 'NA', '#N/A', 'NULL', 'NONE', '', '?', '-', 'INF', '-INF',
    '+INF', 'INFINITY', '-INFINITY', '1.#INF', '-1.#INF', '1.#QNAN'
}


def format_number_for_csv(x):
    """Format numbers for CSV output with Indonesian locale (comma as decimal, dot as thousand)"""
    if pd.isna(x) or x == '':
        return x
    try:
        if isinstance(x, (int, float)):
            if x == int(x):  # Whole number
                return f"{int(x):,d}".replace(",", ".")
            else:  # Decimal number
                return f"{x:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")
        return x
    except:
        return x


def get_store_name_from_filename(filename):
    """Extract store name from filename, handling different patterns."""
    # Remove file extension and split by spaces
    name_parts = Path(filename).stem.split()

    # Handle cases like "002 Miss Glam Pekanbaru.csv" -> "Pekanbaru"
    # or "01 Miss Glam Padang.csv" -> "Padang"
    if len(name_parts) >= 3 and name_parts[1].lower() == 'miss' and name_parts[2].lower() == 'glam':
        return ' '.join(name_parts[3:]).strip().upper()
    elif len(name_parts) >= 2 and name_parts[0].lower() == 'miss' and name_parts[1].lower() == 'glam':
        return ' '.join(name_parts[2:]).strip().upper()
    # Fallback: take everything after the first space
    elif ' ' in filename:
        return ' '.join(name_parts[1:]).strip().upper()
    return name_parts[0].upper()

def read_csv_file_v2(file_path, decimal_sep=',', thousand_sep=None):
    # List of (separator, encoding) combinations to try
    formats_to_try = [
        (',', 'utf-8'),      # Standard CSV with comma
        (';', 'utf-8'),      # Semicolon with UTF-8
        (',', 'latin1'),     # Comma with Latin1
        (';', 'latin1'),     # Semicolon with Latin1
        (',', 'cp1252'),     # Windows-1252 encoding
        (';', 'cp1252')
    ]

    for sep, enc in formats_to_try:
        try:
            df = pd.read_csv(
                file_path,
                sep=sep,
                decimal=decimal_sep,
                thousands=thousand_sep,
                encoding=enc,
                engine='python'  # More consistent behavior with Python engine
            )
            # If we get here, the file was read successfully
            if not df.empty:
                return df
        except (UnicodeDecodeError, pd.errors.ParserError, pd.errors.EmptyDataError) as e:
            continue  # Try next format
        except Exception as e:
            print(f"Unexpected error reading {file_path} with sep='{sep}', encoding='{enc}': {str(e)}")
            continue

    # If we get here, all attempts failed
    print(f"Failed to read {file_path} with any known format")
    return None


# SAVE AND READ functions


# Apply the formatting to numeric columns in your final output
def format_dataframe_display(df):
    # Make a copy to avoid SettingWithCopyWarning
    df_display = df.copy()

    # Apply formatting to numeric columns
    for col in df_display.select_dtypes(include=['int64', 'float64']).columns:
        df_display[col] = df_display[col].apply(
            lambda x: format_id_number(x, 2) if pd.notna(x) else x
        )

    return df_display


def read_excel_file(file_path):
    """
    Read an Excel file with robust error handling for problematic values.
    """
    try:
        print(f"\nReading excel file: {file_path.name}...")

        # First, read the file with openpyxl directly to handle the data more carefully
        from openpyxl import load_workbook

        # Load the workbook
        wb = load_workbook(
            filename=file_path,
            read_only=True,    # Read-only mode is faster and uses less memory
            data_only=True,    # Get the stored value instead of the formula
            keep_links=False   # Don't load external links
        )

        # Get the first sheet
        ws = wb.active

        # Get headers from the first row
        headers = []
        for idx, cell in enumerate(next(ws.iter_rows(values_only=True))):
            header = str(cell).strip() if cell not in (None, '') else f"Column_{idx + 1}"
            headers.append(header)

        # Initialize data rows
        data = []

        # Process each row
        for row in ws.iter_rows(min_row=2, values_only=True):  # Skip header row
            row_data = []
            for cell in row:
                if cell is None:
                    row_data.append('')
                    continue

                cell_str = str(cell).strip()
                if cell_str.upper() in NA_VALUES:
                    row_data.append('')
                else:
                    row_data.append(cell_str)

            # Only add row if it has data
            if any(cell != '' for cell in row_data):
                data.append(row_data)

        # Create DataFrame
        df = pd.DataFrame(data, columns=headers)

        # Normalize column data types
        df = clean_and_convert(df)

        print(f"✅ Successfully processed {file_path.name} with {len(df)} rows")
        return df

    except Exception as e:
        print(f"❌ Error processing {file_path.name}: {str(e)}")
        import traceback
        traceback.print_exc()
        return None


def save_file(df, file_path, file_format='csv', **kwargs):
    """
    Save DataFrame to file with consistent extension and content type.

    Args:
        df: DataFrame to save
        file_path: Path object or string for the output file
        file_format: 'csv' or 'xlsx'
        **kwargs: Additional arguments to pass to to_csv or to_excel

    Returns:
        Path: The path where the file was saved
    """
    # Ensure file_path is a Path object
    file_path = Path(file_path)

    # Ensure the directory exists
    file_path.parent.mkdir(parents=True, exist_ok=True)

    # Ensure the correct file extension
    if not file_path.suffix.lower() == f'.{file_format}':
        file_path = file_path.with_suffix(f'.{file_format}')

    # Make a copy to avoid modifying the original
    df_output = df.copy()

    # Common preprocessing
    if 'SKU' in df_output.columns:
        df_output['SKU'] = df_output['SKU'].astype(str).str.strip()
        if file_format == 'xlsx':
            # For Excel, wrap SKU in ="..." to preserve leading zeros
            df_output['SKU'] = df_output['SKU'].apply(lambda x: f'="{x}"')

    # Format numbers for CSV if needed
    if file_format == 'csv':
        numeric_cols = df_output.select_dtypes(include=['number']).columns
        for col in numeric_cols:
            df_output[col] = df_output[col].apply(format_number_for_csv)

    # Save based on format
    if file_format == 'csv':
        df_output.to_csv(
            file_path,
            index=False,
            sep=';',
            decimal=',',
            encoding='utf-8-sig',
            **kwargs
        )
    elif file_format == 'xlsx':
        with pd.ExcelWriter(file_path, engine="openpyxl") as writer:
            df_output.to_excel(writer, index=False, **kwargs)

            # Format SKU column as text in Excel
            if 'SKU' in df_output.columns:
                ws = writer.sheets[list(writer.sheets.keys())[0]]
                sku_col_idx = df_output.columns.get_loc("SKU") + 1
                for row in ws.iter_rows(
                    min_row=2,  # Skip header
                    max_row=ws.max_row,
                    min_col=sku_col_idx,
                    max_col=sku_col_idx
                ):
                    for cell in row:
                        cell.number_format = numbers.FORMAT_TEXT
    else:
        raise ValueError(f"Unsupported file format: {file_format}")

    print(f"File saved to {file_path}")
    return file_path


def save_to_complete_format(df, filename, file_format='csv', **kwargs):
    """
    Save Complete format file with consistent extension.

    Args:
        df: Input DataFrame
        filename: Output filename (with or without extension)
        file_format: 'csv' or 'xlsx'
        **kwargs: Additional arguments for save_file
    """

    # Ensure output directory exists
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Save with consistent extension
    if file_format == 'xlsx':
        output_path = OUTPUT_DIR / 'xlsx' / filename
    else:
        output_path = OUTPUT_DIR / 'csv' / filename

    return save_file(df, output_path, file_format=file_format, **kwargs)


def save_to_m2_format(df, filename, file_format='csv', **kwargs):
    """
    Save M2 format file with consistent extension.

    Args:
        df: Input DataFrame
        filename: Output filename (with or without extension)
        file_format: 'csv' or 'xlsx'
        **kwargs: Additional arguments for save_file
    """
    # Filter to only include rows with regular PO qty > 0
    df_filtered = df[df['final_updated_regular_po_qty'] > 0].copy()
    df_output = df_filtered[['Toko', 'Brand', 'SKU', 'HPP', 'final_updated_regular_po_qty']]

    # Ensure output directory exists
    OUTPUT_M2_DIR.mkdir(parents=True, exist_ok=True)

    # Save with consistent extension
    output_path = OUTPUT_M2_DIR / filename
    return save_file(df_output, output_path, file_format=file_format, **kwargs)


def save_to_emergency_po_format(df, filename, file_format='csv', **kwargs):
    """
    Save emergency PO format file with consistent extension.

    Args:
        df: Input DataFrame
        filename: Output filename (with or without extension)
        file_format: 'csv' or 'xlsx'
        **kwargs: Additional arguments for save_file
    """
    # Filter to only include rows with emergency PO qty > 0
    df_filtered = df[df['emergency_po_qty'] > 0].copy()
    df_output = df_filtered[[
        'Brand', 'SKU', 'Nama', 'Toko', 'HPP',
        'emergency_po_qty', 'emergency_po_cost'
    ]]

    # Ensure output directory exists
    OUTPUT_EMERGENCY_DIR.mkdir(parents=True, exist_ok=True)

    # Save with consistent extension
    output_path = OUTPUT_EMERGENCY_DIR / filename
    return save_file(df_output, output_path, file_format=file_format, **kwargs)

In [25]:
# Formatter

from pandas import DataFrame

def normalize_date_string(date_str):
    """Convert Indonesian month names to English for consistent parsing."""

    # Month mapping: Indonesian -> English
    month_mapping = {
        'jan': 'jan', 'januari': 'january',
        'feb': 'feb', 'februari': 'february',
        'mar': 'mar', 'maret': 'march',
        'apr': 'apr', 'april': 'april',
        'mei': 'may', 'may': 'may',
        'jun': 'jun', 'juni': 'june',
        'jul': 'jul', 'juli': 'july',
        'agu': 'aug', 'agustus': 'august',
        'sep': 'sep', 'september': 'september',
        'okt': 'oct', 'oktober': 'october',
        'nov': 'nov', 'november': 'november',
        'des': 'dec', 'desember': 'december',
        'dec': 'dec'
    }

    date_lower = str(date_str).lower().strip()
    for indo_month, eng_month in month_mapping.items():
        # Use word boundaries to avoid partial matches
        import re
        date_lower = re.sub(r'\b' + indo_month + r'\b', eng_month, date_lower)

    return date_lower

def getFrameSpecificDate(df: DataFrame, target_date: str):
    """
    Match date columns in DataFrame with target_date, supporting both English and Indonesian month names.

    Args:
        df: DataFrame with date columns
        target_date: Target date string (e.g., "18 Dec 2025" or "18 Des 2025")

    Returns:
        tuple: (matched_columns, filtered_dataframe)
    """
    if df is None or df.empty:
        return [], df

    # Normalize and parse target date
    normalized_target = normalize_date_string(target_date)
    target_ts = pd.to_datetime(normalized_target, dayfirst=True, errors='coerce')

    if pd.isna(target_ts):
        raise ValueError(f"Unable to parse target_date: {target_date} (normalized: {normalized_target})")

    has_year = bool(pd.Series([target_date]).str.contains(r"\b\d{4}\b", regex=True).iloc[0])
    matched_cols = []

    for col in df.columns:
        col_str = str(col).strip()
        normalized_col = normalize_date_string(col_str)
        col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
        if pd.isna(col_ts):
            continue
        if has_year:
            if col_ts.normalize() == target_ts.normalize():
                matched_cols.append(col)
        else:
            if (col_ts.day == target_ts.day) and (col_ts.month == target_ts.month):
                matched_cols.append(col)
    return matched_cols, df.loc[:, matched_cols] if matched_cols else df.iloc[:, 0:0]

In [26]:
# Load Top 100 SKU from specific DIR and Top 100 Special Handlings

TOP100_GDRIVE_FOLDER_ID = "1ZB1hRsExf3vz7Pxx63NQeDNitRiuX4UD"
TOP100_SKU_CACHE = None


def _resolve_top100_dir(default_local_dir=TOP_100_SKU_DIR):
    """Prefer Google Drive Top100 folder; fallback directly to local data/top_100_sku."""

    env_dir = os.environ.get("TOP100_GDRIVE_DIR")
    if env_dir:
        p = Path(env_dir).expanduser()
        if p.exists():
            return p

    return Path(default_local_dir)


def preload_all_top_100_sku(top_100_dir=None, expected_header_keys=None, max_rows=100):
    if top_100_dir is None:
        top_100_dir = _resolve_top100_dir()

    top_100_dir = Path(top_100_dir)
    if not top_100_dir.exists():
        print(f"Top 100 SKU directory does not exist: {top_100_dir}")
        return {}

    store_names = []
    for path in sorted(top_100_dir.glob('*')):
        if not path.is_file():
            continue
        store_names.append(get_store_name_from_filename(path.name))

    store_names = sorted(set([str(s).strip().upper() for s in store_names if str(s).strip()]))

    cache = {}
    for store_name in store_names:
        df_store = load_top_100_sku_for_store(
            store_name,
            top_100_dir=top_100_dir,
            expected_header_keys=expected_header_keys,
            max_rows=max_rows,
        )
        if df_store is not None and not df_store.empty:
            cache[store_name] = df_store

    return cache


def load_top_100_sku_for_store(location, top_100_dir=None, expected_header_keys=None, max_rows=100):
    """Load Top 100 SKU data for a given store.

    This function will:
    - Find the matching Top 100 file for the store in ``top_100_dir``
    - Detect which row actually contains the header (can be on row 1, 2, 3, ...)
    - Read and return the cleaned DataFrame limited to top ``max_rows`` SKUs
    """
    try:
        location_upper = str(location).strip().upper()

        global TOP100_SKU_CACHE
        if isinstance(TOP100_SKU_CACHE, dict) and location_upper in TOP100_SKU_CACHE:
            return TOP100_SKU_CACHE[location_upper]

        if top_100_dir is None:
            top_100_dir = _resolve_top100_dir()

        top_100_dir = Path(top_100_dir)

        if not top_100_dir.exists():
            print(f"Top 100 SKU directory does not exist: {top_100_dir}")
            return None

        # Use the same filename → store name logic to match files
        matching_files = []
        for path in sorted(top_100_dir.glob('*')):
            if not path.is_file():
                continue
            store_name = get_store_name_from_filename(path.name)

            if store_name.upper() == location_upper:
                matching_files.append(path)

        if not matching_files:
            print(f"No Top 100 SKU file found for store: {location_upper}")
            return None

        # If multiple files match, take the first one deterministically
        file_path = matching_files[0]
        print(f"Loading Top 100 SKU for {location_upper} from: {file_path}")

        suffix = file_path.suffix.lower()

        # Step 1: read raw file without assuming header row
        if suffix in ['.xlsx', '.xls']:
            raw_df = pd.read_excel(file_path, header=None, engine='openpyxl')
        else:
            read_ok = False
            raw_df = None
            for sep in [';', ',']:
                for enc in ['utf-8-sig', 'utf-8', 'latin1', 'cp1252']:
                    try:
                        raw_df = pd.read_csv(file_path, header=None, sep=sep, encoding=enc)
                        read_ok = True
                        break
                    except Exception:
                        continue
                if read_ok:
                    break

            if not read_ok or raw_df is None:
                print(f"Failed to read Top 100 SKU file: {file_path}")
                return None

        if raw_df is None or raw_df.empty:
            print(f"Top 100 SKU file is empty: {file_path}")
            return None

                # Step 2: detect which row is the header
        # Strategy:
        #   1. Prefer any row containing a cell equal to "sku" (case-insensitive)
        #   2. Otherwise, take the first non-empty row
        header_row = None
        max_header_search = min(15, len(raw_df))  # look a bit deeper if needed

        for idx in range(max_header_search):
            row_values = raw_df.iloc[idx].astype(str).str.strip()
            lowered = [v.lower() for v in row_values]

            if "sku" in lowered:
                header_row = idx
                break

        if header_row is None:
            # fallback: first non-empty row
            for idx in range(max_header_search):
                if raw_df.iloc[idx].notna().any():
                    header_row = idx
                    break

        # As a final fallback, if still None but we have rows, use row 0
        if header_row is None:
            header_row = 0

        # Step 3: build df from raw_df using that header row
        header = raw_df.iloc[header_row].astype(str).str.strip().tolist()
        data = raw_df.iloc[header_row + 1 :].reset_index(drop=True)
        data.columns = header
        df = data

        # Basic cleaning
        df.columns = df.columns.astype(str).str.strip()

        # Normalize SKU column if present under any casing
        sku_col = None
        for c in df.columns:
            if str(c).strip().lower() == "sku":
                sku_col = c
                break

        if sku_col is not None:
            df[sku_col] = df[sku_col].astype(str).str.strip()
            # also expose as "SKU" for downstream code
            if sku_col != "SKU":
                df["SKU"] = df[sku_col]

        # Drop completely empty rows
        df = df.dropna(how='all')

        # Limit to top N rows
        if max_rows is not None and max_rows > 0:
            df = df.head(max_rows)

        print(f"Loaded Top 100 SKU for {location_upper}: {len(df)} rows")
        return df

    except Exception as e:
        print(f"Error loading Top 100 SKU for {location}: {str(e)}")
        return None


# Preload Top 100 SKU files once to avoid repeated disk reads per store

TOP100_SKU_CACHE = preload_all_top_100_sku(
    top_100_dir=None,  # auto: prefer Google Drive folder, fallback to local
    expected_header_keys=["SKU", "Nama", "Brand", "Toko"],
    max_rows=100,
)

print(f"Preloaded Top100 stores: {len(TOP100_SKU_CACHE)}")

Loading Top 100 SKU for .DS_STORE from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/.DS_Store
Loaded Top 100 SKU for .DS_STORE: 0 rows
Loading Top 100 SKU for ACEH from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/28. Miss Glam Aceh.xlsx
Loaded Top 100 SKU for ACEH: 100 rows
Loading Top 100 SKU for BALIKPAPAN from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/33. Miss Glam Balikpapan.xlsx
Loaded Top 100 SKU for BALIKPAPAN: 100 rows
Loading Top 100 SKU for BANGKA from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/12. Miss Glam Bangka.xlsx
Loaded Top 100 SKU for BANGKA: 100 rows
Loading Top 100 SKU for BENGKULU from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/8. Miss Glam Bengkulu.xlsx
Loaded Top 100 SKU for BENGKULU: 100 rows
Loading Top 100 SKU for BUKITTINGGI from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/4. Miss Glam Bukittinggi.xlsx
Loaded Top 100 SKU for BUKITTINGGI: 100 rows
Loading Top 100 SKU for DAMAR from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/11. Miss Glam Damar.xlsx
Loaded Top 100 SKU for DAMAR: 100 rows
Loading Top 100 SKU for DR. MANSYUR from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/26. Miss Glam Dr. Mansyur.xlsx
Loaded Top 100 SKU for DR. MANSYUR: 100 rows
Loading Top 100 SKU for DUMAI from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/17. Miss Glam Dumai.xlsx
Loaded Top 100 SKU for DUMAI: 100 rows
Loading Top 100 SKU for DURI from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/24. Miss Glam Duri.xlsx
Loaded Top 100 SKU for DURI: 100 rows
Loading Top 100 SKU for HALAT from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/23. Miss Glam Halat.xlsx
Loaded Top 100 SKU for HALAT: 100 rows
Loading Top 100 SKU for JAMBI from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/3. Miss Glam Jambi.xlsx
Loaded Top 100 SKU for JAMBI: 100 rows
Loading Top 100 SKU for KEDATON from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/18. Miss Glam Kedaton.xlsx
Loaded Top 100 SKU for KEDATON: 100 rows
Loading Top 100 SKU for LAMPUNG from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/7. Miss Glam Lampung.xlsx
Loaded Top 100 SKU for LAMPUNG: 100 rows
Loading Top 100 SKU for LUBUK LINGGAU from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/16. Miss Glam Lubuk Linggau.xlsx
Loaded Top 100 SKU for LUBUK LINGGAU: 100 rows
Loading Top 100 SKU for MARPOYAN from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/29. Miss Glam Marpoyan.xlsx
Loaded Top 100 SKU for MARPOYAN: 100 rows
Loading Top 100 SKU for MAYANG from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/31. Miss Glam Mayang.xlsx
Loaded Top 100 SKU for MAYANG: 100 rows
Loading Top 100 SKU for MEDAN from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/9. Miss Glam Medan.xlsx
Loaded Top 100 SKU for MEDAN: 100 rows
Loading Top 100 SKU for MUARO BUNGO from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/6. Miss Glam Muaro bungo.xlsx
Loaded Top 100 SKU for MUARO BUNGO: 100 rows
Loading Top 100 SKU for P. SIDIMPUAN from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/27. Miss Glam P. Sidimpuan.xlsx
Loaded Top 100 SKU for P. SIDIMPUAN: 100 rows
Loading Top 100 SKU for PADANG from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/1. Miss Glam Padang.xlsx
Loaded Top 100 SKU for PADANG: 100 rows
Loading Top 100 SKU for PALEMBANG from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/10. Miss Glam Palembang.xlsx
Loaded Top 100 SKU for PALEMBANG: 100 rows
Loading Top 100 SKU for PANAM from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/5. Miss Glam Panam.xlsx
Loaded Top 100 SKU for PANAM: 100 rows
Loading Top 100 SKU for PASAMAN BARAT from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/22. Miss Glam Pasaman Barat.xlsx
Loaded Top 100 SKU for PASAMAN BARAT: 100 rows
Loading Top 100 SKU for PAYAKUMBUH from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/13. Miss Glam Payakumbuh.xlsx
Loaded Top 100 SKU for PAYAKUMBUH: 100 rows
Loading Top 100 SKU for PEKANBARU from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/2. Miss Glam Pekanbaru.xlsx
Loaded Top 100 SKU for PEKANBARU: 100 rows
Loading Top 100 SKU for RANTAU PRAPAT from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/19. Miss Glam Rantau Prapat.xlsx
Loaded Top 100 SKU for RANTAU PRAPAT: 100 rows
Loading Top 100 SKU for SEI PENUH from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/30. Miss Glam Sei Penuh.xlsx
Loaded Top 100 SKU for SEI PENUH: 100 rows
Loading Top 100 SKU for SOETA from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/32. Miss Glam Soeta.xlsx
Loaded Top 100 SKU for SOETA: 100 rows
Loading Top 100 SKU for SOLOK from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/14. Miss Glam Solok.xlsx
Loaded Top 100 SKU for SOLOK: 100 rows
Loading Top 100 SKU for SUDIRMAN from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/25. Miss Glam Sudirman.xlsx
Loaded Top 100 SKU for SUDIRMAN: 100 rows
Loading Top 100 SKU for SUTOMO from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/21. Miss Glam Sutomo.xlsx
Loaded Top 100 SKU for SUTOMO: 100 rows
Loading Top 100 SKU for TANJUNG PINANG from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/20. Miss Glam Tanjung Pinang.xlsx
Loaded Top 100 SKU for TANJUNG PINANG: 100 rows
Loading Top 100 SKU for TEMBILAHAN from: /Users/andresuchitra/dev/missglam/autopo/notebook/data/top_100_sku/15. Miss Glam Tembilahan.xlsx
Loaded Top 100 SKU for TEMBILAHAN: 100 rows
Preloaded Top100 stores: 33

In [27]:
def _patch_openpyxl_number_casting():
    print("Calling _patch_openpyxl_number_casting...")

    try:
        from openpyxl.worksheet import _reader
        original_cast = _reader._cast_number

        def _safe_cast_number(value):
            # preserve missing values as missing
            if value is None:
                return None

            if isinstance(value, str):
                v = value.strip()
                if v == "" or v.upper() in NA_VALUES:
                    return None

            try:
                return original_cast(value)
            except (ValueError, TypeError):
                if value in (None, ""):
                    return None
                return value

        _reader._cast_number = _safe_cast_number
    except Exception:
        pass

In [28]:
# LOAD Supplier data, and Override merge_with_suppliers to prevent filling supplier data for rows with empty Brand
print("Applying empty-Brand-safe merge_with_suppliers override...")

def load_supplier_data(supplier_path):
    """Load and clean supplier data."""
    print(f"Loading supplier data: {supplier_path}")
    df = pd.read_csv(supplier_path, sep=';', decimal=',').fillna('')
    df['Nama Brand'] = df['Nama Brand'].str.strip()
    return df

def merge_with_suppliers_v1(df_clean, supplier_df):
    """Merge PO data with supplier information."""
    print("Merging with suppliers...")
    
    # Clean supplier data
    supplier_clean = supplier_df.copy()
    supplier_clean['Nama Brand'] = supplier_clean['Nama Brand'].astype(str).str.strip()
    supplier_clean['Nama Store'] = supplier_clean['Nama Store'].astype(str).str.strip()
    
    # Deduplicate to prevent row explosion - Unique Brand+Store
    supplier_clean = supplier_clean.drop_duplicates(subset=['Nama Brand', 'Nama Store'])
    
    # Ensure PO data has clean columns for merging
    df_clean['Brand'] = df_clean['Brand'].astype(str).str.strip()
    df_clean['Toko'] = df_clean['Toko'].astype(str).str.strip()
    
    # 1. Primary Merge: Match on Brand AND Store (Toko)
    # This prioritizes the specific supplier for that store
    merged_df = pd.merge(
        df_clean,
        supplier_clean,
        left_on=['Brand', 'Toko'],
        right_on=['Nama Brand', 'Nama Store'],
        how='left',
        suffixes=('_clean', '_supplier')
    )
    
    # 2. Fallback: For unmatched rows, try to find ANY supplier for that Brand
    # Identify rows where merge failed (Nama Brand is NaN)
    unmatched_mask = merged_df['Nama Brand'].isna()
    
    if unmatched_mask.any():
        print(f"Found {unmatched_mask.sum()} rows without direct store match. Attempting fallback...")
        
        # Get the unmatched rows and drop the empty supplier columns
        unmatched_rows = merged_df[unmatched_mask].copy()
        supplier_cols = [col for col in supplier_clean.columns if col in unmatched_rows.columns and col != 'Brand']
        unmatched_rows = unmatched_rows.drop(columns=supplier_cols)
        
        # Create fallback supplier list (one per brand)
        # We take the first one found for each brand
        fallback_suppliers = supplier_clean.drop_duplicates(subset=['Nama Brand'])
        
        # Merge unmatched rows with fallback suppliers
        matched_fallback = pd.merge(
            unmatched_rows,
            fallback_suppliers,
            left_on='Brand',
            right_on='Nama Brand',
            how='left',
            suffixes=('_clean', '_supplier')
        )
        
        # Combine the initially matched rows with the fallback-matched rows
        matched_initial = merged_df[~unmatched_mask]
        merged_df = pd.concat([matched_initial, matched_fallback], ignore_index=True)
    
    # Clean up supplier columns
    supplier_columns = [
        'ID Supplier', 'Nama Supplier', 'ID Brand', 'ID Store', 
        'Nama Store', 'Hari Order', 'Min. Purchase', 'Trading Term',
        'Promo Factor', 'Delay Factor'
    ]
    for col in supplier_columns:
        if col in merged_df.columns:
            merged_df[col] = merged_df[col].fillna('' if merged_df[col].dtype == 'object' else 0)
    
    return merged_df

def merge_with_suppliers(df_clean, supplier_df):
    """Merge PO data with supplier info, skipping fallback for blank Brand rows."""
    print("Merging with suppliers (override)...")

    import time

    t0 = time.perf_counter()

    supplier_clean = supplier_df.copy()
    supplier_clean['Nama Brand'] = supplier_clean['Nama Brand'].astype(str).str.strip()
    supplier_clean['Nama Store'] = supplier_clean['Nama Store'].astype(str).str.strip()
    supplier_clean = supplier_clean.drop_duplicates(subset=['Nama Brand', 'Nama Store'])

    df_clean = df_clean.copy()
    df_clean['Brand'] = df_clean['Brand'].astype(str).str.strip()
    df_clean['Toko'] = df_clean['Toko'].astype(str).str.strip()

    supplier_by_brand = supplier_clean.drop_duplicates(subset=['Nama Brand']).copy()

    supplier_columns = [
        'ID Supplier', 'Nama Supplier', 'ID Brand', 'ID Store',
        'Nama Store', 'Hari Order', 'Min. Purchase', 'Trading Term',
        'Promo Factor', 'Delay Factor'
    ]
    supplier_columns_present = [c for c in supplier_columns if c in supplier_clean.columns]

    t1 = time.perf_counter()

    merged_primary = pd.merge(
        df_clean,
        supplier_clean,
        left_on=['Brand', 'Toko'],
        right_on=['Nama Brand', 'Nama Store'],
        how='left',
        suffixes=('', '__supplier_brand_store')
    )

    t2 = time.perf_counter()

    merged_fallback = pd.merge(
        df_clean[['Brand']],
        supplier_by_brand[['Nama Brand'] + supplier_columns_present],
        left_on=['Brand'],
        right_on=['Nama Brand'],
        how='left',
        suffixes=('', '__supplier_brand')
    )

    t3 = time.perf_counter()

    brand_clean = merged_primary['Brand'].astype(str).str.strip()
    fallback_mask = merged_primary['Nama Brand'].isna() & (brand_clean != '')

    if fallback_mask.any():
        print(
            f"Found {int(fallback_mask.sum())} rows without store match; attempting brand-only fallback for non-empty brands..."
        )
        for col in supplier_columns_present:
            if col in merged_primary.columns and col in merged_fallback.columns:
                merged_primary.loc[fallback_mask, col] = merged_fallback.loc[fallback_mask, col]
        if 'Nama Brand' in merged_primary.columns and 'Nama Brand' in merged_fallback.columns:
            merged_primary.loc[fallback_mask, 'Nama Brand'] = merged_fallback.loc[fallback_mask, 'Nama Brand']
        if 'Nama Store' in merged_primary.columns:
            merged_primary.loc[fallback_mask, 'Nama Store'] = ''

    t4 = time.perf_counter()

    for col in supplier_columns_present:
        if col in merged_primary.columns:
            merged_primary[col] = merged_primary[col].fillna('' if merged_primary[col].dtype == 'object' else 0)

    t5 = time.perf_counter()

    print(
        "[TIMING] suppliers: prep={:.2f}s primary_merge={:.2f}s fallback_merge={:.2f}s apply_fallback={:.2f}s fillna={:.2f}s total={:.2f}s".format(
            (t1 - t0),
            (t2 - t1),
            (t3 - t2),
            (t4 - t3),
            (t5 - t4),
            (t5 - t0),
        )
    )

    return merged_primary

Applying empty-Brand-safe merge_with_suppliers override...

In [29]:
# Special SKU handling - load special SKU rules from sku_special.xlsx
# This file contains SKU-specific days cover rules that override the default 30 days

SPECIAL_SKU_PATH = BASE_DIR / 'data/sku_special.xlsx'
SPECIAL_SKU_RULES_CACHE = None


def load_special_sku_rules(force_reload: bool = False):
    """Load special SKU rules from sku_special.xlsx file.
    
    Returns:
        pd.DataFrame: DataFrame with columns ['SKU', 'Brand', 'Produk', 'Toko', 'Days Cover']
                      or None if file doesn't exist or can't be loaded
    """
    global SPECIAL_SKU_RULES_CACHE

    if not force_reload and isinstance(SPECIAL_SKU_RULES_CACHE, pd.DataFrame):
        return SPECIAL_SKU_RULES_CACHE

    try:
        if not SPECIAL_SKU_PATH.exists():
            print(f"Special SKU file not found: {SPECIAL_SKU_PATH}")
            SPECIAL_SKU_RULES_CACHE = None
            return None
        
        df = pd.read_excel(SPECIAL_SKU_PATH)
        
        # Validate required columns
        required_cols = ['SKU', 'Toko', 'Days Cover']
        missing_cols = [col for col in required_cols if col not in df.columns]
        if missing_cols:
            print(f"Warning: Special SKU file missing columns: {missing_cols}")
            SPECIAL_SKU_RULES_CACHE = None
            return None
        
        # Clean and normalize data
        df['SKU'] = df['SKU'].astype(str).str.strip()
        df['Toko'] = df['Toko'].astype(str).str.strip().str.upper()
        df['Days Cover'] = pd.to_numeric(df['Days Cover'], errors='coerce').fillna(30).astype(int)
        
        print(f"Loaded {len(df)} special SKU rules from {SPECIAL_SKU_PATH.name}")
        SPECIAL_SKU_RULES_CACHE = df
        return df
        
    except Exception as e:
        print(f"Error loading special SKU rules: {str(e)}")
        SPECIAL_SKU_RULES_CACHE = None
        return None


def apply_special_sku(df, store_location=None):
    """Apply special SKU days cover rules based on sku_special.xlsx.
    
    This function modifies the 'target_days_cover' column for SKUs that have
    special rules defined in the sku_special.xlsx file.
    
    Args:
        df (pd.DataFrame): DataFrame with SKU and target_days_cover columns
        store_location (str): Store location name (e.g., 'PADANG', 'BALIKPAPAN')
    
    Returns:
        pd.DataFrame: DataFrame with updated target_days_cover values
    """
    if store_location is None:
        return df
    
    # Load special SKU rules
    special_rules = load_special_sku_rules()
    if special_rules is None or special_rules.empty:
        return df
    
    # Normalize store location for matching
    store_location_upper = str(store_location).strip().upper()
    
    # Filter rules for this store (including ALL STORE rules)
    store_rules = special_rules[
        (special_rules['Toko'] == store_location_upper) | 
        (special_rules['Toko'] == 'ALL STORE')
    ].copy()
    
    if store_rules.empty:
        return df
    
    # Ensure SKU column exists and is normalized in df
    if 'SKU' not in df.columns:
        print(f"Warning: SKU column not found in dataframe for {store_location}")
        return df
    
    df['SKU'] = df['SKU'].astype(str).str.strip()
    
    # Create a mapping of SKU -> Days Cover
    # If a SKU appears in both ALL STORE and specific store, specific store takes precedence
    sku_days_map = {}
    
    # First add ALL STORE rules
    all_store_rules = store_rules[store_rules['Toko'] == 'ALL STORE']
    for _, row in all_store_rules.iterrows():
        sku_days_map[row['SKU']] = row['Days Cover']
    
    # Then add/override with specific store rules
    specific_store_rules = store_rules[store_rules['Toko'] == store_location_upper]
    for _, row in specific_store_rules.iterrows():
        sku_days_map[row['SKU']] = row['Days Cover']
    
    # Apply the special days cover to matching SKUs
    if sku_days_map:
        df['target_days_cover'] = df.apply(
            lambda row: sku_days_map.get(row['SKU'], row['target_days_cover']),
            axis=1
        )
        
        matched_count = df['SKU'].isin(sku_days_map.keys()).sum()
        print(f"Applied special SKU days cover to {matched_count} rows for store {store_location}")
    
    return df

In [30]:
# main entry point execution

_patch_openpyxl_number_casting()

os.makedirs(OUTPUT_DIR, exist_ok=True)

EXCLUDE_BRANDS = ['WARDAH', 'MAKE OVER','OMG','EMINA','LABORE','KAHF','INSTAPERFECT','PUTRI','EARTH LOVE LIFE','TAVI','CRYSTALLURE','BIODEF']

STORES_18_DEC = [
    'Padang', 'Pekanbaru', 'Jambi', 'Bukittinggi', 'Muaro Bungo', 'Bengkulu', 'Medan', 'Palembang', 'Damar', 'Payakumbuh', 'Solok',
    'Lubuk Linggau', 'Kedaton', 'Dumai', 'Rantau Prapat', 'Tanjung Pinang', 'Sutomo', 'Pasaman Barat', 'Halat', 'Aceh', 'Mayang', 'Soeta'
]

STORES_17_DEC = ['Lampung', 'Bangka', 'Tembilahan', 'Duri', 'P. Sidimpuan', 'Sei Penuh']

TOP100_STOCK_ABS_MAX = 1e12  # clamp sentinel/garbage magnitudes (e.g. ±9.223e18) to 0

def _normalize_store_key(value: str) -> str:
    """Normalize store strings so small formatting differences don't break merges.

    Examples:
    - 'Miss Glam Halat' -> 'missglamhalat'
    - 'Missglam Halat'  -> 'missglamhalat'
    """
    import re
    if value is None:
        return ''
    return re.sub(r'[^a-z0-9]+', '', str(value).strip().lower())

def _sanitize_top100_stock(series: pd.Series) -> pd.Series:
    # Keep missing as NaN (do NOT fillna(0)), so we can fall back to previous day / original stock.
    # 0 is a VALID stock value if present in the file.

    s = series.copy()

    # 0) Normalize ALL missing (including NaT) to np.nan early
    s = s.where(~pd.isna(s), np.nan)

    # 1) If datetime-like, convert to object so we don't accidentally numeric-convert datetimes
    if pd.api.types.is_datetime64_any_dtype(s):
        s = s.astype("object")
        s = s.where(~pd.isna(s), np.nan)

    # 2) Replace NA-like string tokens to NaN (safe even if series has mixed types)
    s = s.replace(list(NA_VALUES), np.nan)

    # 3) Only strip if the element is actually a string (DO NOT astype(str))
    if s.dtype == "object":
        s = s.apply(lambda x: x.strip() if isinstance(x, str) else x)
        s = s.replace("", np.nan)

    # 4) Convert to numeric; non-numeric -> NaN
    s = pd.to_numeric(s, errors="coerce")

    # 5) Clamp absurd garbage magnitudes to 0 (NaN stays NaN)
    s = s.mask(s.abs() > TOP100_STOCK_ABS_MAX, 0)

    # 6) Replace infinities to 0
    s = s.replace([np.inf, -np.inf], 0)

    return s

def _build_stock_top100_map(df_top_100, running_date):
    """
    Build SKU+Toko -> stock_top100 mapping from date-specific column.
    Fallback order (0 is VALID):
    1) Use running_date column (e.g. 18 Dec)
    2) If NULL/empty -> use day before column (e.g. 17 Dec)
    3) If NULL/empty -> keep NaN (caller will use ORIGINAL store stock)
    """

    if df_top_100 is None or df_top_100.empty:
        print("  [DEBUG] _build_stock_top100_map: df_top_100 is None or empty")
        return None
    if 'SKU' not in df_top_100.columns:
        print("  [DEBUG] _build_stock_top100_map: 'SKU' column not found in df_top_100")
        return None
    if 'Toko' not in df_top_100.columns:
        print("  [DEBUG] _build_stock_top100_map: 'Toko' column not found in df_top_100")
        return None
    if not running_date:
        print("  [DEBUG] _build_stock_top100_map: running_date is None or empty")
        return None
    
    matched_cols, _ = getFrameSpecificDate(df_top_100, running_date)
    if not matched_cols:
        print(f"  [DEBUG] _build_stock_top100_map: No date column matched for '{running_date}'")
        print(f"  [DEBUG] Available columns: {df_top_100.columns.tolist()}")
        return None
    stock_date_col = matched_cols[0]
    print(f"  [DEBUG] _build_stock_top100_map: Using date column '{stock_date_col}' for running_date '{running_date}'")
    
    from datetime import timedelta
    try:
        running_dt = pd.to_datetime(running_date, dayfirst=True)
        day_before = running_dt - timedelta(days=1)
        day_before_str = day_before.strftime('%d %b %Y')
        matched_cols_before, _ = getFrameSpecificDate(df_top_100, day_before_str)
        stock_date_col_before = matched_cols_before[0] if matched_cols_before else None
        if stock_date_col_before:
            print(f"  [DEBUG] _build_stock_top100_map: Found fallback column '{stock_date_col_before}' for day before")
    except:
        stock_date_col_before = None
        print("  [DEBUG] _build_stock_top100_map: Could not determine day before column")
    
    top = df_top_100[['SKU', 'Toko', stock_date_col]].copy()
    
    if stock_date_col_before and stock_date_col_before in df_top_100.columns:
        top['stock_day_before'] = df_top_100[stock_date_col_before]
    else:
        top['stock_day_before'] = np.nan
    
    top['SKU'] = top['SKU'].astype(str).str.strip()
    top['Toko'] = top['Toko'].astype(str).str.strip()
    top['stock_target_date'] = _sanitize_top100_stock(top[stock_date_col])
    top['stock_day_before'] = _sanitize_top100_stock(top['stock_day_before'])

    # IMPORTANT: 0 is VALID, so fallback ONLY when NaN (missing), not when 0.
    top['stock_top100'] = top['stock_target_date'].where(
        top['stock_target_date'].notna(),
        top['stock_day_before']
    )

    top['stock_top100'] = _sanitize_top100_stock(top['stock_top100'])
    top['toko_key'] = top['Toko'].apply(_normalize_store_key)
    used_target = top['stock_target_date'].notna().sum()
    used_day_before = (top['stock_target_date'].isna() & top['stock_day_before'].notna()).sum()
    will_use_original = top['stock_top100'].isna().sum()
    
    print(
        f"  [DEBUG] Stock source breakdown: {used_target} from target date, "
        f"{used_day_before} from day before, {will_use_original} will use original stock"
    )
    
    top = top[['SKU', 'toko_key', 'stock_top100']]
    top = top.dropna(subset=['SKU', 'toko_key'])
    top = top.drop_duplicates(subset=['SKU', 'toko_key'], keep='first')
    print(f"  [DEBUG] _build_stock_top100_map: Built map with {len(top)} SKU+toko_key combinations")

    return top

def calculate_inventory_metrics(df_clean, store_location=None):
    """
    Calculate various inventory metrics including safety stock, reorder points, and PO quantities.

    Args:
        df_clean (pd.DataFrame): Input dataframe with required columns
        store_location (str): Store location for applying special SKU rules

    Returns:
        pd.DataFrame: Dataframe with added calculated columns
    """
    import numpy as np
    import pandas as pd

    # Ensure we're working with a copy to avoid SettingWithCopyWarning
    df = df_clean.copy()

    # Set display options
    pd.set_option('display.float_format', '{:.2f}'.format)

    # Ensure final_stock exists for metrics, without relying on stock_top100 later in the function
    # if 'final_stock' not in df.columns:
    #     if 'stock_top100' in df.columns:
    #         df['final_stock'] = df['stock_top100']
    #     else:
    #         base_stock_col = 'Stok' if 'Stok' in df.columns else 'Stock'
    #         df['final_stock'] = df[base_stock_col] if base_stock_col in df.columns else 0

    base_stock_col = 'Stok' if 'Stok' in df.columns else 'Stock'

    # IMPORTANT!! - 22 Dec update -> use original 'Stok' column
    df['final_stock'] = df[base_stock_col]
    metric_stock_col = 'final_stock'

    # Ensure is_top_100_sku exists (0 for non-top-100 by default)
    if 'is_top_100_sku' not in df.columns:
        df['is_top_100_sku'] = 0
    df['is_top_100_sku'] = pd.to_numeric(df['is_top_100_sku'], errors='coerce').fillna(0).astype(int)

    # Force the columns we need into numeric form
    numeric_cols = [
        base_stock_col, metric_stock_col, 'Daily Sales', 'Max. Daily Sales', 'Lead Time',
        'Max. Lead Time', 'Sedang PO', 'HPP', 'Harga', 'sales_contribution'
    ]
    for col in numeric_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

    try:
        # 1. Safety stock calculation
        df['Safety stock'] = (df['Max. Daily Sales'] * df['Max. Lead Time']) - (df['Daily Sales'] * df['Lead Time'])
        df['Safety stock'] = df['Safety stock'].apply(lambda x: np.ceil(x)).fillna(0).astype(int)

        # 2. Reorder point calculation
        df['Reorder point'] = np.ceil((df['Daily Sales'] * df['Lead Time']) + df['Safety stock']).fillna(0).astype(int)

        # 3. Stock cover - default to 30 days for all SKUs
        df['target_days_cover'] = 30

        # Apply special SKU rules if store location provided
        if store_location:
            df = apply_special_sku(df, store_location)

        # Calculate target days cover based on the determined days
        df['qty_for_target_days_cover'] = (
            df['Daily Sales'] * df['target_days_cover']
        ).apply(lambda x: np.ceil(x)).fillna(0).astype(int)

        df['current_days_stock_cover'] = np.where(
            df['Daily Sales'] > 0,
            df[metric_stock_col] / df['Daily Sales'],
            0
        )

        # 5. Is open PO flag
        df['is_open_po'] = np.where(
            (df['current_days_stock_cover'] < df['target_days_cover']) &
            (df[metric_stock_col] <= df['Reorder point']), 1, 0
        )

        # 6. Initial PO quantity
        df['initial_qty_po'] = np.where(
            df['Daily Sales'] == 0,
            0,
            df['qty_for_target_days_cover'] - df[metric_stock_col] - df.get('Sedang PO', 0)
        )

        df['initial_qty_po'] = (
            pd.Series(
                np.where(df['is_open_po'] == 1, df['initial_qty_po'], 0),
                index=df.index
            )
            .clip(lower=0)
            .astype(int)
        )

        # 7. Emergency PO quantity
        #    For non top-100 SKUs, this must always be 0
        base_emergency = np.where(
            df.get('Sedang PO', 0) > 0,
            np.maximum(0, (df['Max. Lead Time'] - df['current_days_stock_cover']) * df['Daily Sales']),
            np.ceil((df['Max. Lead Time'] - df['current_days_stock_cover']) * df['Daily Sales'])
        )
        df['emergency_po_qty'] = base_emergency * df['is_top_100_sku']

        # Clean up emergency PO quantities
        df['emergency_po_qty'] = (
            df['emergency_po_qty']
            .replace([np.inf, -np.inf], 0)
            .fillna(0)
            .clip(lower=0)
            .astype(int)
        )

        # 8. Updated regular PO quantity:
        # it will be same as initial suggested PO both for SKU Top 100 and others
        df['updated_regular_po_qty'] = df['initial_qty_po'].clip(lower=0).astype(int)

        # 9. Final updated regular PO quantity (enforce minimum order)
        df['final_updated_regular_po_qty'] = np.where(
            (df['updated_regular_po_qty'] > 0) &
            (df['updated_regular_po_qty'] < df['Min. Order']),
            df['Min. Order'],
            df['updated_regular_po_qty']
        ).astype(int)

        # 10. Calculate costs
        df['emergency_po_cost'] = (df['emergency_po_qty'] * df['HPP']).round(2)
        df['final_updated_regular_po_cost'] = (df['final_updated_regular_po_qty'] * df['HPP']).round(2)

        # Clean up any remaining NaN or infinite values
        df = df.fillna(0)

        return df

    except Exception as e:
        print(f"Error in calculate_inventory_metrics: {str(e)}")
        return df_clean

def clean_po_data(df, location=None):
    """Clean and prepare PO data with contribution calculations."""
    try:
        # Create a copy to avoid modifying the original DataFrame
        df = df.copy()
        # remove duplicate SKU
        df = df.drop_duplicates(subset=['SKU'], keep='first')

        # Keep original column names but strip any extra whitespace
        df.columns = df.columns.str.strip()

        # Define required columns (using original case)
        required_columns = [
            'Brand', 'Kategori Brand', 'SKU', 'Nama', 'Toko', 'Stok',
            'Daily Sales', 'Max. Daily Sales', 'Lead Time',
            'Max. Lead Time', 'Min. Order', 'Sedang PO', 'HPP', 'Harga'
        ]

        # Find actual column names in the DataFrame (case-sensitive)
        available_columns = {col.strip(): col for col in df.columns}
        columns_to_keep = []

        for col in required_columns:
            if col in available_columns:
                columns_to_keep.append(available_columns[col])
            else:
                print(f"Warning: Column '{col}' not found in input data")
                # Add as empty column if it's required
                if col in ['Brand', 'SKU', 'HPP', 'Harga']:  # These are critical
                    df[col] = ''

        # Select only the columns we need
        df = df[[col for col in columns_to_keep if col in df.columns]]

        # Check for missing required columns
        missing_columns = [col for col in ['Brand', 'SKU', 'HPP', 'Harga'] if col not in df.columns]
        if missing_columns:
            raise ValueError(
                f"Missing required columns: {missing_columns}. "
                f"Available columns: {df.columns.tolist()}"
            )

        # Clean brand column
        if 'Brand' in df.columns:
            df['Brand'] = df['Brand'].astype(str).str.strip()

        # Convert SKU to string and clean it
        if 'SKU' in df.columns:
            df['SKU'] = df['SKU'].astype(str).str.strip()

        if 'Toko' in df.columns:
            df['Toko'] = df['Toko'].astype(str).str.strip()

        # Convert numeric columns with better error handling
        numeric_columns = [
            'Stok', 'Daily Sales', 'Max. Daily Sales', 'Lead Time',
            'Max. Lead Time', 'Sedang PO', 'HPP', 'Min. Order', 'Harga'
        ]

        for col in numeric_columns:
            if col in df.columns:
                try:
                    # First convert to string, clean, then to numeric
                    df[col] = (
                        df[col]
                        .astype(str)
                        .str.replace(r'[^\d.,-]', '', regex=True)  # Remove non-numeric except .,-
                        .str.replace(',', '.', regex=False)         # Convert commas to decimal points
                        .replace('', '0')                           # Empty strings to '0'
                        .astype(float)                              # Convert to float
                        .fillna(0)                                  # Fill any remaining NaNs with 0
                    )
                except Exception as e:
                    print(f"Warning: Could not convert column '{col}' to numeric: {str(e)}")
                    df[col] = 0  # Set to 0 if conversion fails

        # calculate sales contribution
        df['sales_contribution'] = df['Daily Sales'] * df['Harga']

        # remove stock_top100 column, replaced by final_stock
        if 'stock_top100' in df.columns:
            df = df.drop(columns=['stock_top100'])

        return df

    except Exception as e:
        print(f"Error in clean_po_data: {str(e)}")
        import traceback
        traceback.print_exc()
        return None

def _find_sku_col(cols):
    for c in cols:
        if str(c).strip().lower() == "sku":
            return c
    return None

def process_po_file(file_path, supplier_df, running_date=None):
    """Process a single PO file and return merged data and summary."""
    print(f"\nProcessing PO file: {file_path.name} ....")

    try:
        # Extract location from filename using the new function
        location = get_store_name_from_filename(file_path.name)
        print(f"  - Extracted location: {location}")

        # Read the CSV with error handling
        try:
            is_excel = file_path.suffix.lower() in ['.xlsx', '.xls']

            # Try reading with different encodings if needed
            if is_excel:
                df = read_excel_file(file_path)
            else:
                df = read_csv_file_v2(file_path, decimal_sep='.')

            # Check if DataFrame is empty
            if df is None or df.empty:
                raise ValueError("File is empty")

            # Clean the data
            df_clean = clean_po_data(df, location)
            # Skip if cleaning failed
            if df_clean is None or df_clean.empty:
                raise ValueError("Data cleaning failed")

            # --- Top 100 SKU handling ---
            df_top_100 = load_top_100_sku_for_store(
                location,
                expected_header_keys=["SKU", "Nama", "Brand", "Toko"]
            )

            # Set is_top_100_sku flag using _find_sku_col for flexible column matching
            top_sku_col = _find_sku_col(df_top_100.columns) if df_top_100 is not None else None
            clean_sku_col = _find_sku_col(df_clean.columns)

            print(f"  [DEBUG] top_sku_col: {top_sku_col}, clean_sku_col: {clean_sku_col}")

            if (
                df_top_100 is not None
                and not df_top_100.empty
                and top_sku_col is not None
                and clean_sku_col is not None
            ):
                top_skus = set(df_top_100[top_sku_col].astype(str).str.strip())
                print(f"  [DEBUG] Found {len(top_skus)} Top 100 SKUs")
                print(f"  [DEBUG] Sample Top 100 SKUs: {list(top_skus)[:5]}")

                df_clean["is_top_100_sku"] = (
                    df_clean[clean_sku_col].astype(str).str.strip().isin(top_skus).astype(int)
                )

                top_100_count = df_clean["is_top_100_sku"].sum()
                print(f"  [DEBUG] Marked {top_100_count} rows as Top 100 SKUs in df_clean")
            else:
                print(f"  - No valid Top 100 data for {location}, setting is_top_100_sku = 0")
                df_clean["is_top_100_sku"] = 0

            # stock_top100: use date-specific stock for top-100 rows, else fallback to original stock
            base_stock_col = 'Stok' if 'Stok' in df_clean.columns else 'Stock'
            if base_stock_col in df_clean.columns:
                df_clean['stock_top100'] = pd.to_numeric(df_clean[base_stock_col], errors='coerce').fillna(0)
            else:
                df_clean['stock_top100'] = 0

            print(f"  [DEBUG] Initialized stock_top100 with base stock column '{base_stock_col}'")
            print(f"  [DEBUG] df_clean has 'Toko' column: {'Toko' in df_clean.columns}")
            
            if 'Toko' in df_clean.columns:
                print(f"  [DEBUG] Sample Toko values in df_clean: {df_clean['Toko'].unique()[:5].tolist()}")

            top_stock_map = _build_stock_top100_map(df_top_100, running_date)
            if (
                top_stock_map is not None
                and 'SKU' in df_clean.columns
                and 'Toko' in df_clean.columns
            ):
                df_clean['SKU'] = df_clean['SKU'].astype(str).str.strip()
                df_clean['Toko'] = df_clean['Toko'].astype(str).str.strip()
                df_clean['toko_key'] = df_clean['Toko'].apply(_normalize_store_key)

                print(f"  [DEBUG] Merging top_stock_map on ['SKU', 'toko_key']")
                df_clean = df_clean.merge(
                    top_stock_map,
                    on=['SKU', 'toko_key'],
                    how='left',
                    suffixes=('', '_top')
                )

                # Count how many rows got matched
                matched_count = df_clean['stock_top100_top'].notna().sum() if 'stock_top100_top' in df_clean.columns else 0
                print(f"  [DEBUG] Merge matched {matched_count} rows with Top 100 stock data")
                    
                # IMPORTANT:
                # - Only overwrite stock for Top-100 rows
                # - Only overwrite when Top-100 stock is REALLY present (numeric after parsing)
                #   Empty cell in Excel may arrive as '' which is "notna" but should NOT overwrite.
                if 'stock_top100_top' in df_clean.columns and 'is_top_100_sku' in df_clean.columns:
                    replacement_raw = df_clean['stock_top100_top']
                    # Convert to numeric first; blanks/strings become NaN
                    replacement_num = pd.to_numeric(replacement_raw, errors='coerce')
                    # Sanitize outliers / infinities (keep NaN as NaN so fallback works)
                    replacement_num = replacement_num.mask(replacement_num.abs() > TOP100_STOCK_ABS_MAX, 0)
                    replacement_num = replacement_num.replace([np.inf, -np.inf], 0)
                    # Overwrite only when:
                    # - SKU is top100
                    # - replacement_num is NOT NaN (means 18 Dec or 17 Dec had a value)
                    mask = (df_clean['is_top_100_sku'].astype(int) == 1) & (replacement_num.notna())
                    df_clean.loc[mask, 'stock_top100'] = replacement_num.loc[mask]
                # Keep stock_top100 numeric (base already numeric); NaN shouldn't exist here, but enforce safely
                df_clean['stock_top100'] = pd.to_numeric(df_clean['stock_top100'], errors='coerce').fillna(0)
                df_clean['stock_top100'] = df_clean['stock_top100'].mask(df_clean['stock_top100'].abs() > TOP100_STOCK_ABS_MAX, 0)
                if 'stock_top100_top' in df_clean.columns:
                    df_clean = df_clean.drop(columns=['stock_top100_top'])
                if 'toko_key' in df_clean.columns:
                    df_clean = df_clean.drop(columns=['toko_key'])
                # Final check
                top_100_with_special_stock = ((df_clean['is_top_100_sku'] == 1) & (df_clean['stock_top100'] != df_clean[base_stock_col])).sum()
                print(f"  [DEBUG] {top_100_with_special_stock} Top 100 SKUs have different stock_top100 values")

            print(f"After excluding specific brands for {location} - current count: ({len(df_clean)})")

            # calculate metrics PO
            df_clean = calculate_inventory_metrics(df_clean, store_location=location)

            # Merge with suppliers
            merged_df = merge_with_suppliers(df_clean, supplier_df)
            # Generate summary
            padang_count = (merged_df['Nama Store'] == 'Miss Glam Padang').sum()
            other_supplier_count = ((merged_df['Nama Store'] != 'Miss Glam Padang') &
                                  (merged_df['Nama Store'] != '')).sum()

            summary = {
                'file': file_path.name,
                'location': location,
                'total_rows': len(merged_df),
                'padang_suppliers': int(padang_count),
                'other_suppliers': int(other_supplier_count),
                'no_supplier': int((merged_df['Nama Store'] == '').sum()),
                'status': 'Success'
            }

            return merged_df, summary

        except Exception as e:
            raise Exception(f"Error processing file data: {str(e)}")

    except Exception as e:
        error_msg = f"Error processing {file_path.name}: {str(e)}"
        print(f"  - {error_msg}")
        return None, {
            'file': file_path.name,
            'location': location if 'location' in locals() else 'Unknown',
            'total_rows': 0,
            'padang_suppliers': 0,
            'other_suppliers': 0,
            'no_supplier': 0,
            'status': f"Error: {str(e)[:100]}"
        }

def exclude_specific_brands(df, exclude_brands):
    """Exclude rows where 'Nama' is in the exclude_brands list."""
    return df[~df['Brand'].isin(exclude_brands)]

def clean_and_convert(df):
    """Clean and convert DataFrame columns to appropriate types."""
    if df is None or df.empty:
        return df

    # Make a copy to avoid SettingWithCopyWarning
    df = df.copy()

    # Convert all columns to string first to handle NaN/None consistently
    for col in df.columns:
        df[col] = df[col].astype(str)

    # Define NA values that should be treated as empty/missing
    na_values = list(NA_VALUES)

    # Process each column
    for col in df.columns:
        # Replace NA values with empty string first (treating them as literals, not regex)
        df[col] = df[col].replace(na_values, '', regex=False)

        # Skip empty columns
        if df[col].empty:
            continue

        # Convert numeric columns
        if col in NUMERIC_COLUMNS:
            # Convert to numeric, coercing errors to NaN, then fill with 0
            df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)
        else:
            # For non-numeric columns, ensure they're strings and strip whitespace
            df[col] = df[col].astype(str).str.strip()
            df[col] = df[col].replace('', np.nan).fillna('')
            df[col] = df[col].infer_objects(copy=False)

    return df

from concurrent.futures import ThreadPoolExecutor, as_completed

def main():
    # Load data
    supplier_df = load_supplier_data(SUPPLIER_PATH)
    all_summaries = []
    run_date = '20251222'
    running_date = datetime.strptime(run_date, '%Y%m%d').strftime('%d %b %Y')
    CURRENT_DIR = INPUT_DIR / run_date

    # Configure output root: output/YYYYMMDD/{complete,excel,m2,emergency}
    configure_output_dirs(run_date)

    # Patch openpyxl casting (kept as-is)
    _patch_openpyxl_number_casting()

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    os.makedirs(OUTPUT_EXCEL_DIR, exist_ok=True)
    os.makedirs(OUTPUT_M2_DIR, exist_ok=True)
    os.makedirs(OUTPUT_EMERGENCY_DIR, exist_ok=True)

    print(f"Running date for Top 100 stock: {running_date}")

    def _save_outputs(df_to_save: pd.DataFrame, filename: str):
        df_to_save = df_to_save.copy()

        # Ensure final_stock remains available in outputs
        if 'final_stock' not in df_to_save.columns:
            if 'stock_top100' in df_to_save.columns:
                df_to_save['final_stock'] = df_to_save['stock_top100']
            else:
                base_stock_col = 'Stok' if 'Stok' in df_to_save.columns else ('Stock' if 'Stock' in df_to_save.columns else None)
                if base_stock_col is not None:
                    df_to_save['final_stock'] = df_to_save[base_stock_col]

        # Do NOT write internal helper column
        df_to_save = df_to_save.drop(columns=['stock_top100'], errors='ignore')

        save_to_complete_format(df_to_save, filename, file_format='xlsx')
        save_to_complete_format(df_to_save, filename)
        save_to_m2_format(df_to_save, filename)
        save_to_emergency_po_format(df_to_save, filename)

    save_futures = []
    max_workers = int(os.environ.get('SAVE_WORKERS', '2'))

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        # Process each PO file
        for file_path in sorted(CURRENT_DIR.glob('*')):
            try:
                merged_df, summary = process_po_file(file_path, supplier_df, running_date=running_date)

                # Snapshot df for background thread safety
                df_snapshot = merged_df.copy()

                # Kick off file writes asynchronously so we can proceed to the next store
                save_futures.append(executor.submit(_save_outputs, df_snapshot, file_path.name))

                output_path = OUTPUT_DIR / file_path.name
                summary['output_path'] = str(output_path)

                # Print progress
                print(f"  - Location: {summary['location']}")
                print(f"  - Rows processed: {summary['total_rows']}")
                print(f"  - 'Miss Glam Padang' suppliers: {summary['padang_suppliers']} rows")
                print(f"  - Other suppliers: {summary['other_suppliers']} rows")
                print(f"  - No supplier data: {summary['no_supplier']} rows")
                print(f"  - Scheduled saves for: {output_path}")

                all_summaries.append(summary)

            except Exception as e:
                print(f"Error processing {file_path.name}: {str(e)}")
                continue

        # Ensure all background saves completed
        for fut in as_completed(save_futures):
            try:
                fut.result()
            except Exception as e:
                print(f"Error during background save: {str(e)}")

    # Display final summary
    if all_summaries:
        print("\nProcessing complete! Summary:")
        summary_df = pd.DataFrame(all_summaries)
        display(summary_df)

        # Show sample of last processed file
        print("\nSample of the last processed file:")
        display(merged_df)
    else:
        print("\nNo files were processed successfully.")


# Run the main function
if __name__ == "__main__":
    main()

Calling _patch_openpyxl_number_casting...
Loading supplier data: /Users/andresuchitra/dev/missglam/autopo/notebook/data/supplier.csv
Calling _patch_openpyxl_number_casting...
Running date for Top 100 stock: 22 Dec 2025

Processing PO file: 1. Miss Glam Padang.csv ....
  - Extracted location: PADANG
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8993137708319', '8993137006538', '8997225412300', '8993137718936', '8991038775171']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Padang']
  [DEBUG] _build_stock_top100_map: Using date column '2025-12-22 00:00:00' for running_date '22 Dec 2025'
  [DEBUG] _build_stock_top100_map: Found fallback column '2025-12-21 00:00:00' for day before
  [DEBUG] Stock source breakdown: 0 from target date, 0 from day before, 100 will use original stock
  [DEBUG] _build_stock_top100_map: Built map with 100 SKU+toko_key combinations
  [DEBUG] Merging top_stock_map on ['SKU', 'toko_key']
  [DEBUG] Merge matched 0 rows with Top 100 stock data
  [DEBUG] 0 Top 100 SKUs have different stock_top100 values
After excluding specific brands for PADANG - current count: (37278)
Loaded 268 special SKU rules from sku_special.xlsx

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)

Applied special SKU days cover to 249 rows for store PADANG
Merging with suppliers (override)...
Found 26164 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.02s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.07s
  - Location: PADANG
  - Rows processed: 37278
  - 'Miss Glam Padang' suppliers: 11114 rows
  - Other suppliers: 0 rows
  - No supplier data: 26164 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/1. Miss Glam Padang.csv

Processing PO file: 10. Miss Glam Palembang.csv ....
  - Extracted location: PALEMBANG
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8993137708319', '30200186137', '10300514242', '8993137718936', '8991038775171']
  [DEBUG] Marked 99 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Palembang']
  [DEBUG] _build_stock_top100_map: Using date column '2025-12-22 00:00:00' for running_date '22 Dec 2025'
  [DEBUG] _build_stock_top100_map: Found fallback column '2025-12-21 00:00:00' for day before
  [DEBUG] Stock source breakdown: 0 from target date, 0 from day before, 100 will use original stock
  [DEBUG] _build_stock_top100_map: Built map with 100 SKU+toko_key combinations
  [DEBUG] Merging top_stock_map on ['SKU', 'toko_key']

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)

  [DEBUG] Merge matched 0 rows with Top 100 stock data
  [DEBUG] 0 Top 100 SKUs have different stock_top100 values
After excluding specific brands for PALEMBANG - current count: (36856)
Applied special SKU days cover to 245 rows for store PALEMBANG
Merging with suppliers (override)...
Found 26361 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=1.68s primary_merge=0.27s fallback_merge=0.02s apply_fallback=0.42s fillna=0.22s total=2.61s
  - Location: PALEMBANG
  - Rows processed: 36856
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10495 rows
  - No supplier data: 26361 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/10. Miss Glam Palembang.csv

Processing PO file: 11. Miss Glam Damar.csv ....
  - Extracted location: DAMAR
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8993137708319', '8993137006538', '8993137718936', '8991038775171', '041554590913']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Damar']
  [DEBUG] _build_stock_top100_map: No date column matched for '22 Dec 2025'
  [DEBUG] Available columns: ['No.', 'Brand', 'SKU', 'Nama', 'Toko', 'Ada di grosir (sumber terdekat dan tercepat) atau tidak?', '2025-12-09 00:00:00', '2025-12-10 00:00:00', '2025-12-11 00:00:00', '2025-12-12 00:00:00', '2025-12-13 00:00:00', '2025-12-14 00:00:00', '2025-12-15 00:00:00', '2025-12-16 00:00:00', '2025-12-17 00:00:00', '2025-12-18 00:00:00']
After excluding specific brands for DAMAR - current count: (37472)

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')

Applied special SKU days cover to 248 rows for store DAMAR
Merging with suppliers (override)...
Found 26337 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=1.19s primary_merge=0.34s fallback_merge=0.11s apply_fallback=1.06s fillna=0.83s total=3.53s
  - Location: DAMAR
  - Rows processed: 37472
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 11135 rows
  - No supplier data: 26337 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/11. Miss Glam Damar.csv

Processing PO file: 12. Miss Glam Bangka.csv ....
  - Extracted location: BANGKA
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8998824552817', '10500637314', '10300514242', '8993137718936', '8991038775171']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Bangka']
  [DEBUG] _build_stock_top100_map: Using date column '2025-12-22 00:00:00' for running_date '22 Dec 2025'
  [DEBUG] _build_stock_top100_map: Found fallback column '2025-12-21 00:00:00' for day before
  [DEBUG] Stock source breakdown: 0 from target date, 0 from day before, 100 will use original stock
  [DEBUG] _build_stock_top100_map: Built map with 100 SKU+toko_key combinations

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)

  [DEBUG] Merging top_stock_map on ['SKU', 'toko_key']
  [DEBUG] Merge matched 0 rows with Top 100 stock data
  [DEBUG] 0 Top 100 SKUs have different stock_top100 values
After excluding specific brands for BANGKA - current count: (36826)
Applied special SKU days cover to 241 rows for store BANGKA
Merging with suppliers (override)...
Found 26426 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.30s primary_merge=0.20s fallback_merge=0.09s apply_fallback=0.10s fillna=0.01s total=0.69s
  - Location: BANGKA
  - Rows processed: 36826
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10400 rows
  - No supplier data: 26426 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/12. Miss Glam Bangka.csv

Processing PO file: 13. Miss Glam Payakumbuh.csv ....
  - Extracted location: PAYAKUMBUH
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8993137708319', '8809623612735', '8993137006538', '745604685900', '8991038775171']
  [DEBUG] Marked 98 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Payakumbuh']
  [DEBUG] _build_stock_top100_map: No date column matched for '22 Dec 2025'
  [DEBUG] Available columns: ['No.', 'Brand', 'SKU', 'Nama', 'Toko', 'Ada di grosir (sumber terdekat dan tercepat) atau tidak?', '2025-12-09 00:00:00', '2025-12-10 00:00:00', '2025-12-11 00:00:00', '2025-12-12 00:00:00', '2025-12-13 00:00:00', '2025-12-14 00:00:00', '2025-12-15 00:00:00', '2025-12-16 00:00:00', '2025-12-17 00:00:00', '2025-12-18 00:00:00']
After excluding specific brands for PAYAKUMBUH - current count: (36917)

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')

Applied special SKU days cover to 247 rows for store PAYAKUMBUH
Merging with suppliers (override)...
Found 26218 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.41s primary_merge=0.18s fallback_merge=0.04s apply_fallback=0.56s fillna=0.15s total=1.34s
  - Location: PAYAKUMBUH
  - Rows processed: 36917
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10699 rows
  - No supplier data: 26218 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/13. Miss Glam Payakumbuh.csv

Processing PO file: 14. Miss Glam Solok.csv ....
  - Extracted location: SOLOK
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8993137708319', '8809623612735', '10500637314', '10300514242', '8993137006538']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Solok']
  [DEBUG] _build_stock_top100_map: No date column matched for '22 Dec 2025'
  [DEBUG] Available columns: ['', 'Brand', 'SKU', 'Nama', 'Toko', 'Ada di grosir (sumber terdekat dan tercepat) atau tidak?', '2025-12-09 00:00:00', '2025-12-10 00:00:00', '2025-12-11 00:00:00', '2025-12-12 00:00:00', '2025-12-13 00:00:00', '2025-12-14 00:00:00', '2025-12-15 00:00:00', '2025-12-16 00:00:00', '2025-12-17 00:00:00', '2025-12-18 00:00:00', '2025-12-19 00:00:00', '2025-12-20 00:00:00', '2025-12-21 00:00:00']
After excluding specific brands for SOLOK - current count: (36905)

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')

Applied special SKU days cover to 243 rows for store SOLOK
Merging with suppliers (override)...
Found 26204 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.34s primary_merge=0.12s fallback_merge=0.04s apply_fallback=0.42s fillna=0.17s total=1.10s
  - Location: SOLOK
  - Rows processed: 36905
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10701 rows
  - No supplier data: 26204 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/14. Miss Glam Solok.csv

Processing PO file: 15. Miss Glam Tembilahan.csv ....
  - Extracted location: TEMBILAHAN
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8998824552817', '8993137708319', '8809623612735', '10500637314', '20100464055']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Tembilahan']
  [DEBUG] _build_stock_top100_map: No date column matched for '22 Dec 2025'
  [DEBUG] Available columns: ['No.', 'Brand', 'SKU', 'Nama', 'Toko', 'Produk ada atau tidak (di grosir terdekat & tercepat)', '2025-12-09 00:00:00', '2025-12-10 00:00:00', '2025-12-11 00:00:00', '2025-12-12 00:00:00', '2025-12-13 00:00:00', '2025-12-14 00:00:00', '2025-12-15 00:00:00', '2025-12-16 00:00:00', '17-Des-2025', '18-Des-2025']
After excluding specific brands for TEMBILAHAN - current count: (36779)

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')

Applied special SKU days cover to 241 rows for store TEMBILAHAN
Merging with suppliers (override)...
Found 26273 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.01s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.06s
  - Location: TEMBILAHAN
  - Rows processed: 36779
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10506 rows
  - No supplier data: 26273 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/15. Miss Glam Tembilahan.csv

Processing PO file: 16. Miss Glam Lubuk Linggau.csv ....
  - Extracted location: LUBUK LINGGAU
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8998824552817', '8993137708319', '8993137006538', '8993137718936', '745604685900']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Lubuk Linggau']
  [DEBUG] _build_stock_top100_map: Using date column '2025-12-22 00:00:00' for running_date '22 Dec 2025'
  [DEBUG] _build_stock_top100_map: Found fallback column '2025-12-21 00:00:00' for day before
  [DEBUG] Stock source breakdown: 0 from target date, 0 from day before, 100 will use original stock
  [DEBUG] _build_stock_top100_map: Built map with 100 SKU+toko_key combinations
  [DEBUG] Merging top_stock_map on ['SKU', 'toko_key']
  [DEBUG] Merge matched 0 rows with Top 100 stock data
  [DEBUG] 0 Top 100 SKUs have different stock_top100 values
After excluding specific brands for LUBUK LINGGAU - current count: (36799)

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)

Applied special SKU days cover to 239 rows for store LUBUK LINGGAU
Merging with suppliers (override)...
Found 26669 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.02s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.07s
  - Location: LUBUK LINGGAU
  - Rows processed: 36799
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10130 rows
  - No supplier data: 26669 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/16. Miss Glam Lubuk Linggau.csv

Processing PO file: 17. Miss Glam Dumai.csv ....
  - Extracted location: DUMAI
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8998824552817', '8993137708319', '8809623612735', '30200186137', '10300514242']
  [DEBUG] Marked 97 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Dumai']
  [DEBUG] _build_stock_top100_map: No date column matched for '22 Dec 2025'
  [DEBUG] Available columns: ['No.', 'Brand', 'SKU', 'Nama', 'Toko', 'Ada di grosir (sumber terdekat dan tercepat) atau tidak?', '2025-12-09 00:00:00', '2025-12-10 00:00:00', '2025-12-11 00:00:00', '2025-12-12 00:00:00', '2025-12-13 00:00:00', '2025-12-14 00:00:00', '2025-12-15 00:00:00', '2025-12-16 00:00:00', '2025-12-17 00:00:00', '2025-12-18 00:00:00']
After excluding specific brands for DUMAI - current count: (36887)
Applied special SKU days cover to 244 rows for store DUMAI

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')

Merging with suppliers (override)...
Found 26259 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.02s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.06s
  - Location: DUMAI
  - Rows processed: 36887
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10628 rows
  - No supplier data: 26259 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/17. Miss Glam Dumai.csv

Processing PO file: 18. Miss Glam Kedaton.csv ....
  - Extracted location: KEDATON
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8998824552817', '8993137708319', '10300514242', '8993137006538', '8993137718936']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Kedaton']
  [DEBUG] _build_stock_top100_map: Using date column '2025-12-22 00:00:00' for running_date '22 Dec 2025'
  [DEBUG] _build_stock_top100_map: Found fallback column '2025-12-21 00:00:00' for day before
  [DEBUG] Stock source breakdown: 0 from target date, 0 from day before, 100 will use original stock
  [DEBUG] _build_stock_top100_map: Built map with 100 SKU+toko_key combinations
  [DEBUG] Merging top_stock_map on ['SKU', 'toko_key']
  [DEBUG] Merge matched 0 rows with Top 100 stock data
  [DEBUG] 0 Top 100 SKUs have different stock_top100 values
After excluding specific brands for KEDATON - current count: (36847)

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)

Applied special SKU days cover to 247 rows for store KEDATON
Merging with suppliers (override)...
Found 26388 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.01s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.06s
  - Location: KEDATON
  - Rows processed: 36847
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10459 rows
  - No supplier data: 26388 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/18. Miss Glam Kedaton.csv

Processing PO file: 19. Miss Glam Rantau Prapat.csv ....
  - Extracted location: RANTAU PRAPAT
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8993137708319', '8809623612735', '10300514242', '8993137006538', '8993137718936']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Rantau Prapat']
  [DEBUG] _build_stock_top100_map: No date column matched for '22 Dec 2025'
  [DEBUG] Available columns: ['No.', 'Brand', 'SKU', 'Nama', 'Toko', 'Produk ada atau tidak (di grosir terdekat & tercepat)', '2025-12-09 00:00:00', '2025-12-10 00:00:00', '2025-12-11 00:00:00', '2025-12-12 00:00:00', '2025-12-13 00:00:00', '2025-12-14 00:00:00', '2025-12-15 00:00:00', '2025-12-16 00:00:00', '2025-12-17 00:00:00', '2025-12-18 00:00:00']
After excluding specific brands for RANTAU PRAPAT - current count: (36785)
Applied special SKU days cover to 245 rows for store RANTAU PRAPAT

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')

Merging with suppliers (override)...
Found 26342 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.04s primary_merge=0.02s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.09s
  - Location: RANTAU PRAPAT
  - Rows processed: 36785
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10443 rows
  - No supplier data: 26342 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/19. Miss Glam Rantau Prapat.csv

Processing PO file: 2. Miss Glam Pekanbaru.csv ....
  - Extracted location: PEKANBARU
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8998824552817', '8993137708319', '10300514242', '8998824553340', '041554590913']
  [DEBUG] Marked 99 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Pekanbaru']
  [DEBUG] _build_stock_top100_map: Using date column '2025-12-22 00:00:00' for running_date '22 Dec 2025'
  [DEBUG] _build_stock_top100_map: Found fallback column '2025-12-21 00:00:00' for day before
  [DEBUG] Stock source breakdown: 0 from target date, 0 from day before, 100 will use original stock
  [DEBUG] _build_stock_top100_map: Built map with 100 SKU+toko_key combinations
  [DEBUG] Merging top_stock_map on ['SKU', 'toko_key']
  [DEBUG] Merge matched 0 rows with Top 100 stock data
  [DEBUG] 0 Top 100 SKUs have different stock_top100 values
After excluding specific brands for PEKANBARU - current count: (37108)

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)

Applied special SKU days cover to 247 rows for store PEKANBARU
Merging with suppliers (override)...
Found 26273 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.01s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.07s
  - Location: PEKANBARU
  - Rows processed: 37108
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10835 rows
  - No supplier data: 26273 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/2. Miss Glam Pekanbaru.csv

Processing PO file: 20. Miss Glam Tanjung Pinang.csv ....
  - Extracted location: TANJUNG PINANG
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['10300514242', '8991038775171', '041554590913', '8992821101306', '8993137692335']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Tanjung Pinang']
  [DEBUG] _build_stock_top100_map: Using date column '2025-12-22 00:00:00' for running_date '22 Dec 2025'
  [DEBUG] _build_stock_top100_map: Found fallback column '2025-12-21 00:00:00' for day before
  [DEBUG] Stock source breakdown: 0 from target date, 0 from day before, 100 will use original stock
  [DEBUG] _build_stock_top100_map: Built map with 100 SKU+toko_key combinations
  [DEBUG] Merging top_stock_map on ['SKU', 'toko_key']
  [DEBUG] Merge matched 0 rows with Top 100 stock data
  [DEBUG] 0 Top 100 SKUs have different stock_top100 values
After excluding specific brands for TANJUNG PINANG - current count: (36717)

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)

Applied special SKU days cover to 237 rows for store TANJUNG PINANG
Merging with suppliers (override)...
Found 26404 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.02s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.07s
  - Location: TANJUNG PINANG
  - Rows processed: 36717
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10313 rows
  - No supplier data: 26404 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/20. Miss Glam Tanjung Pinang.csv

Processing PO file: 21. Miss Glam Sutomo.csv ....
  - Extracted location: SUTOMO
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8993137708319', '10300514242', '8993137006538', '8993137718936', '8998824553340']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Sutomo']
  [DEBUG] _build_stock_top100_map: Using date column '2025-12-22 00:00:00' for running_date '22 Dec 2025'
  [DEBUG] _build_stock_top100_map: Found fallback column '2025-12-21 00:00:00' for day before
  [DEBUG] Stock source breakdown: 0 from target date, 0 from day before, 100 will use original stock
  [DEBUG] _build_stock_top100_map: Built map with 100 SKU+toko_key combinations
  [DEBUG] Merging top_stock_map on ['SKU', 'toko_key']
  [DEBUG] Merge matched 0 rows with Top 100 stock data
  [DEBUG] 0 Top 100 SKUs have different stock_top100 values
After excluding specific brands for SUTOMO - current count: (37131)

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)

Applied special SKU days cover to 248 rows for store SUTOMO
Merging with suppliers (override)...
Found 26257 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.02s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.07s
  - Location: SUTOMO
  - Rows processed: 37131
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10874 rows
  - No supplier data: 26257 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/21. Miss Glam Sutomo.csv

Processing PO file: 22. Miss Glam Pasaman Barat.csv ....
  - Extracted location: PASAMAN BARAT
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8991748012252', '8993137708319', '8809623612735', '10300514242', '8997225412300']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Pasaman Barat']
  [DEBUG] _build_stock_top100_map: No date column matched for '22 Dec 2025'
  [DEBUG] Available columns: ['No.', 'Brand', 'SKU', 'Nama', 'Toko', 'Ada di grosir (sumber terdekat dan tercepat) atau tidak?', '2025-12-09 00:00:00', '2025-12-10 00:00:00', '2025-12-11 00:00:00', '2025-12-12 00:00:00', '2025-12-13 00:00:00', '2025-12-14 00:00:00', '2025-12-15 00:00:00', '2025-12-16 00:00:00', '2025-12-17 00:00:00', '2025-12-18 00:00:00', '2025-12-19 00:00:00']
After excluding specific brands for PASAMAN BARAT - current count: (36782)
Applied special SKU days cover to 245 rows for store PASAMAN BARAT

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')

Merging with suppliers (override)...
Found 26217 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.02s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.07s
  - Location: PASAMAN BARAT
  - Rows processed: 36782
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10565 rows
  - No supplier data: 26217 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/22. Miss Glam Pasaman Barat.csv

Processing PO file: 23. Miss Glam Halat.csv ....
  - Extracted location: HALAT
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['10400618143', '810114870341', '8993137708319', '30200186137', '10300514242']
  [DEBUG] Marked 99 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Halat']
  [DEBUG] _build_stock_top100_map: No date column matched for '22 Dec 2025'
  [DEBUG] Available columns: ['No.', 'Brand', 'SKU', 'Nama', 'Toko', 'Produk ada atau tidak (di grosir terdekat & tercepat)', '2025-12-09 00:00:00', '2025-12-10 00:00:00', '2025-12-11 00:00:00', '2025-12-12 00:00:00', '2025-12-13 00:00:00', '2025-12-14 00:00:00', '2025-12-15 00:00:00', '2025-12-16 00:00:00', '2025-12-17 00:00:00', '2025-12-18 00:00:00']
After excluding specific brands for HALAT - current count: (36899)

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')

Applied special SKU days cover to 247 rows for store HALAT
Merging with suppliers (override)...
Found 25925 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.01s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.06s
  - Location: HALAT
  - Rows processed: 36899
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10974 rows
  - No supplier data: 25925 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/23. Miss Glam Halat.csv

Processing PO file: 24. Miss Glam Duri.csv ....
  - Extracted location: DURI
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8993137708319', '10300514242', '8991038775171', '8998824553340', '8992821101306']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Duri']
  [DEBUG] _build_stock_top100_map: No date column matched for '22 Dec 2025'
  [DEBUG] Available columns: ['NO', 'Brand', 'SKU', 'Nama', 'Toko', 'Ada di grosir (sumber terdekat dan tercepat) atau tidak?', '2025-12-09 00:00:00', '2025-12-10 00:00:00', '2025-12-11 00:00:00', '2025-12-12 00:00:00', '2025-12-13 00:00:00', '2025-12-14 00:00:00', '2025-12-15 00:00:00', '2025-12-16 00:00:00', '2025-12-17 00:00:00', '2025-12-18 00:00:00', '2025-12-19 00:00:00']
After excluding specific brands for DURI - current count: (36836)

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')

Applied special SKU days cover to 246 rows for store DURI
Merging with suppliers (override)...
Found 26251 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.01s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.06s
  - Location: DURI
  - Rows processed: 36836
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10585 rows
  - No supplier data: 26251 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/24. Miss Glam Duri.csv

Processing PO file: 25. Miss Glam Sudirman.csv ....
  - Extracted location: SUDIRMAN
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8993137708319', '30200186137', '10300514242', '8993137718936', '041554590913']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Sudirman']
  [DEBUG] _build_stock_top100_map: No date column matched for '22 Dec 2025'
  [DEBUG] Available columns: ['No.', 'Brand', 'SKU', 'Nama', 'Toko', 'Produk ada atau tidak (di grosir terdekat & tercepat)', '2025-12-09 00:00:00', '2025-12-10 00:00:00', '2025-12-11 00:00:00', '2025-12-12 00:00:00', '2025-12-13 00:00:00', '2025-12-14 00:00:00', '2025-12-15 00:00:00', '2025-12-16 00:00:00', '2025-12-17 00:00:00', '2025-12-18 00:00:00']
After excluding specific brands for SUDIRMAN - current count: (37210)

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')

Applied special SKU days cover to 246 rows for store SUDIRMAN
Merging with suppliers (override)...
Found 26376 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.01s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.07s
  - Location: SUDIRMAN
  - Rows processed: 37210
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10834 rows
  - No supplier data: 26376 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/25. Miss Glam Sudirman.csv

Processing PO file: 26. Miss Glam Dr. Mansyur.csv ....
  - Extracted location: DR. MANSYUR
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['810114870341', '8993137708319', '20100493603', '10300514242', '8992222073851']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Dr. Mansyur']
  [DEBUG] _build_stock_top100_map: No date column matched for '22 Dec 2025'
  [DEBUG] Available columns: ['No.', 'Brand', 'SKU', 'Nama', 'Toko', 'Produk ada atau tidak (di grosir terdekat & tercepat)', '2025-12-09 00:00:00', '2025-12-10 00:00:00', '2025-12-11 00:00:00', '2025-12-12 00:00:00', '2025-12-13 00:00:00', '14-Des-2025', '15-Des-25', '16-Des-25', '17-Des-25', '18-Des-25']
After excluding specific brands for DR. MANSYUR - current count: (36873)
Applied special SKU days cover to 248 rows for store DR. MANSYUR

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')

Merging with suppliers (override)...
Found 25960 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.01s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.06s
  - Location: DR. MANSYUR
  - Rows processed: 36873
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10913 rows
  - No supplier data: 25960 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/26. Miss Glam Dr. Mansyur.csv

Processing PO file: 27. Miss Glam P. Sidimpuan.csv ....
  - Extracted location: P. SIDIMPUAN
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['10400618143', '8993137708319', '8809623612735', '10300514242', '8993137006538']
  [DEBUG] Marked 99 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam P. Sidimpuan']
  [DEBUG] _build_stock_top100_map: No date column matched for '22 Dec 2025'
  [DEBUG] Available columns: ['No.', 'Brand', 'SKU', 'Nama', 'Toko', 'Produk ada atau tidak (di grosir terdekat & tercepat)', '2025-12-09 00:00:00', '2025-12-10 00:00:00', '2025-12-11 00:00:00', '2025-12-12 00:00:00', '2025-12-13 00:00:00', '2025-12-14 00:00:00', '2025-12-15 00:00:00', '2025-12-16 00:00:00', '2025-12-17 00:00:00', '2025-12-18 00:00:00', '2025-12-19 00:00:00', '2025-12-20 00:00:00']
After excluding specific brands for P. SIDIMPUAN - current count: (36813)
Applied special SKU days cover to 244 rows for store P. SIDIMPUAN

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')

Merging with suppliers (override)...
Found 26443 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.01s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.06s
  - Location: P. SIDIMPUAN
  - Rows processed: 36813
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10370 rows
  - No supplier data: 26443 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/27. Miss Glam P. Sidimpuan.csv

Processing PO file: 28. Miss Glam Aceh.csv ....
  - Extracted location: ACEH
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8993137708319', '8809416470016', '30200186137', '8993137718936', '8991038775171']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Aceh']
  [DEBUG] _build_stock_top100_map: No date column matched for '22 Dec 2025'
  [DEBUG] Available columns: ['No.', 'Brand', 'SKU', 'Nama', 'Toko', 'Produk ada atau tidak (di grosir terdekat & tercepat)', '2025-12-09 00:00:00', '2025-12-10 00:00:00', '2025-12-11 00:00:00', '2025-12-12 00:00:00', '2025-12-13 00:00:00', '2025-12-14 00:00:00', '2025-12-15 00:00:00', '2025-12-16 00:00:00', '2025-12-17 00:00:00', '2025-12-18 00:00:00']
After excluding specific brands for ACEH - current count: (36742)
Applied special SKU days cover to 239 rows for store ACEH

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')

Merging with suppliers (override)...
Found 26515 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.01s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.06s
  - Location: ACEH
  - Rows processed: 36742
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10227 rows
  - No supplier data: 26515 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/28. Miss Glam Aceh.csv

Processing PO file: 29. Miss Glam Marpoyan.csv ....
  - Extracted location: MARPOYAN
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8993137708319', '30200186137', '10300514242', '8993137006538', '8993137718936']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Marpoyan']
  [DEBUG] _build_stock_top100_map: No date column matched for '22 Dec 2025'
  [DEBUG] Available columns: ['No.', 'Brand', 'SKU', 'Nama', 'Toko', 'Produk ada atau tidak (di grosir terdekat & tercepat)', '2025-12-09 00:00:00', '2025-12-10 00:00:00', '2025-12-11 00:00:00', '2025-12-12 00:00:00', '2025-12-13 00:00:00', '2025-12-14 00:00:00', '2025-12-15 00:00:00', '2025-12-16 00:00:00', '2025-12-17 00:00:00', '2025-12-18 00:00:00']
After excluding specific brands for MARPOYAN - current count: (36905)

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')

Applied special SKU days cover to 243 rows for store MARPOYAN
Merging with suppliers (override)...
Found 26377 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.02s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.08s
  - Location: MARPOYAN
  - Rows processed: 36905
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10528 rows
  - No supplier data: 26377 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/29. Miss Glam Marpoyan.csv

Processing PO file: 3. Miss Glam Jambi.csv ....
  - Extracted location: JAMBI
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8993137708319', '30200186137', '10300514242', '8993137718936', '8991038775171']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Jambi']
  [DEBUG] _build_stock_top100_map: Using date column '2025-12-22 00:00:00' for running_date '22 Dec 2025'
  [DEBUG] _build_stock_top100_map: Found fallback column '2025-12-21 00:00:00' for day before
  [DEBUG] Stock source breakdown: 0 from target date, 0 from day before, 100 will use original stock
  [DEBUG] _build_stock_top100_map: Built map with 100 SKU+toko_key combinations
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/1. Miss Glam Padang.xlsx
  [DEBUG] Merging top_stock_map on ['SKU', 'toko_key']
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/10. Miss Glam Palembang.xlsx

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)

  [DEBUG] Merge matched 0 rows with Top 100 stock data
  [DEBUG] 0 Top 100 SKUs have different stock_top100 values
After excluding specific brands for JAMBI - current count: (36943)
Applied special SKU days cover to 240 rows for store JAMBI
Merging with suppliers (override)...
Found 26368 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.09s primary_merge=0.06s fallback_merge=0.02s apply_fallback=0.13s fillna=0.03s total=0.33s
  - Location: JAMBI
  - Rows processed: 36943
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10575 rows
  - No supplier data: 26368 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/3. Miss Glam Jambi.csv

Processing PO file: 30. Miss Glam Sei Penuh.csv ....
  - Extracted location: SEI PENUH
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/1. Miss Glam Padang.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/10. Miss Glam Palembang.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/1. Miss Glam Padang.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/1. Miss Glam Padang.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/10. Miss Glam Palembang.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/10. Miss Glam Palembang.csv
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8993137708319', '8809623612735', '10300514242', '8993137006538', '8993137718936']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Sei Penuh']
  [DEBUG] _build_stock_top100_map: Using date column '2025-12-22 00:00:00' for running_date '22 Dec 2025'
  [DEBUG] _build_stock_top100_map: Found fallback column '2025-12-21 00:00:00' for day before
  [DEBUG] Stock source breakdown: 0 from target date, 0 from day before, 100 will use original stock

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)

  [DEBUG] _build_stock_top100_map: Built map with 100 SKU+toko_key combinations
  [DEBUG] Merging top_stock_map on ['SKU', 'toko_key']
  [DEBUG] Merge matched 0 rows with Top 100 stock data
  [DEBUG] 0 Top 100 SKUs have different stock_top100 values
After excluding specific brands for SEI PENUH - current count: (36809)
Applied special SKU days cover to 247 rows for store SEI PENUH
Merging with suppliers (override)...
Found 26522 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=1.45s primary_merge=0.44s fallback_merge=0.17s apply_fallback=2.02s fillna=0.40s total=4.48s
  - Location: SEI PENUH
  - Rows processed: 36809
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10287 rows
  - No supplier data: 26522 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/30. Miss Glam Sei Penuh.csv

Processing PO file: 31. Miss Glam Mayang.csv ....
  - Extracted location: MAYANG
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8998824552817', '10300514242', '8993137718936', '8991038775171', '041554590913']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Mayang']
  [DEBUG] _build_stock_top100_map: Using date column '2025-12-22 00:00:00' for running_date '22 Dec 2025'
  [DEBUG] _build_stock_top100_map: Found fallback column '2025-12-21 00:00:00' for day before
  [DEBUG] Stock source breakdown: 0 from target date, 0 from day before, 100 will use original stock

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)

  [DEBUG] _build_stock_top100_map: Built map with 100 SKU+toko_key combinations
  [DEBUG] Merging top_stock_map on ['SKU', 'toko_key']
  [DEBUG] Merge matched 0 rows with Top 100 stock data
  [DEBUG] 0 Top 100 SKUs have different stock_top100 values
After excluding specific brands for MAYANG - current count: (36816)
Applied special SKU days cover to 241 rows for store MAYANG
Merging with suppliers (override)...
Found 26826 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=1.06s primary_merge=0.86s fallback_merge=0.34s apply_fallback=1.26s fillna=0.34s total=3.86s
  - Location: MAYANG
  - Rows processed: 36816
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 9990 rows
  - No supplier data: 26826 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/31. Miss Glam Mayang.csv

Processing PO file: 32. Miss Glam Soeta.csv ....
  - Extracted location: SOETA
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8993137708319', '8809623612735', '8993137710428', '10300514242', '8993137006538']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Soeta']
  [DEBUG] _build_stock_top100_map: Using date column '2025-12-22 00:00:00' for running_date '22 Dec 2025'
  [DEBUG] _build_stock_top100_map: Found fallback column '2025-12-21 00:00:00' for day before
  [DEBUG] Stock source breakdown: 0 from target date, 0 from day before, 100 will use original stock
  [DEBUG] _build_stock_top100_map: Built map with 100 SKU+toko_key combinations
  [DEBUG] Merging top_stock_map on ['SKU', 'toko_key']

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)

  [DEBUG] Merge matched 0 rows with Top 100 stock data
  [DEBUG] 0 Top 100 SKUs have different stock_top100 values
After excluding specific brands for SOETA - current count: (37303)
Applied special SKU days cover to 249 rows for store SOETA
Merging with suppliers (override)...
Found 30822 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.22s primary_merge=0.02s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.27s
  - Location: SOETA
  - Rows processed: 37303
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 6481 rows
  - No supplier data: 30822 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/32. Miss Glam Soeta.csv

Processing PO file: 33. Miss Glam Balikpapan.csv ....
  - Extracted location: BALIKPAPAN
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['30200186137', '10300514242', '30400360011', '8993137718936', '8991038775171']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Balikpapan']
  [DEBUG] _build_stock_top100_map: No date column matched for '22 Dec 2025'
  [DEBUG] Available columns: ['No.', 'Brand', 'SKU', 'Nama', 'Toko', 'Produk ada atau tidak (di grosir terdekat & tercepat)', '2025-12-09 00:00:00', '2025-12-10 00:00:00', '2025-12-11 00:00:00', '2025-12-12 00:00:00', '2025-12-13 00:00:00', '2025-12-14 00:00:00', '2025-12-15 00:00:00', '2025-12-16 00:00:00', '2025-12-17 00:00:00', '2025-12-18 00:00:00']
After excluding specific brands for BALIKPAPAN - current count: (37081)
Applied special SKU days cover to 251 rows for store BALIKPAPAN

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')

Merging with suppliers (override)...
Found 30407 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.01s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.06s
  - Location: BALIKPAPAN
  - Rows processed: 37081
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 6674 rows
  - No supplier data: 30407 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/33. Miss Glam Balikpapan.csv

Processing PO file: 34. Miss Glam Pematang Siantar.csv ....
  - Extracted location: PEMATANG SIANTAR
No Top 100 SKU file found for store: PEMATANG SIANTAR
  [DEBUG] top_sku_col: None, clean_sku_col: SKU
  - No valid Top 100 data for PEMATANG SIANTAR, setting is_top_100_sku = 0
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Pematang Siantar']
  [DEBUG] _build_stock_top100_map: df_top_100 is None or empty
After excluding specific brands for PEMATANG SIANTAR - current count: (37763)
Applied special SKU days cover to 249 rows for store PEMATANG SIANTAR
Merging with suppliers (override)...
Found 37763 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.01s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.06s
  - Location: PEMATANG SIANTAR
  - Rows processed: 37763
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 0 rows
  - No supplier data: 37763 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/34. Miss Glam Pematang Siantar.csv

Processing PO file: 35. Miss Glam Batoh.csv ....
  - Extracted location: BATOH
No Top 100 SKU file found for store: BATOH
  [DEBUG] top_sku_col: None, clean_sku_col: SKU
  - No valid Top 100 data for BATOH, setting is_top_100_sku = 0
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Batoh']
  [DEBUG] _build_stock_top100_map: df_top_100 is None or empty
After excluding specific brands for BATOH - current count: (37749)
Applied special SKU days cover to 249 rows for store BATOH
Merging with suppliers (override)...
Found 37749 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.02s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.08s
  - Location: BATOH
  - Rows processed: 37749
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 0 rows
  - No supplier data: 37749 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/35. Miss Glam Batoh.csv

Processing PO file: 4. Miss Glam Bukittinggi.csv ....
  - Extracted location: BUKITTINGGI
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8998824552817', '8993137708319', '8809623612735', '10300514242', '8993137006538']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Bukittinggi']
  [DEBUG] _build_stock_top100_map: Using date column '2025-12-22 00:00:00' for running_date '22 Dec 2025'
  [DEBUG] _build_stock_top100_map: Found fallback column '2025-12-21 00:00:00' for day before
  [DEBUG] Stock source breakdown: 0 from target date, 0 from day before, 100 will use original stock
  [DEBUG] _build_stock_top100_map: Built map with 100 SKU+toko_key combinations
  [DEBUG] Merging top_stock_map on ['SKU', 'toko_key']
  [DEBUG] Merge matched 0 rows with Top 100 stock data
  [DEBUG] 0 Top 100 SKUs have different stock_top100 values
After excluding specific brands for BUKITTINGGI - current count: (36915)

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)

Applied special SKU days cover to 247 rows for store BUKITTINGGI
Merging with suppliers (override)...
Found 26189 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.02s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.07s
  - Location: BUKITTINGGI
  - Rows processed: 36915
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10726 rows
  - No supplier data: 26189 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/4. Miss Glam Bukittinggi.csv

Processing PO file: 5. Miss Glam Panam.csv ....
  - Extracted location: PANAM
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8998824552817', '8993137708319', '10500637314', '8809623612735', '8993137006538']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Panam']
  [DEBUG] _build_stock_top100_map: No date column matched for '22 Dec 2025'
  [DEBUG] Available columns: ['No.', 'Brand', 'SKU', 'Nama', 'Toko', 'Produk ada atau tidak (di grosir terdekat & tercepat)', '2025-12-09 00:00:00', '2025-12-10 00:00:00', '2025-12-11 00:00:00', '2025-12-12 00:00:00', '2025-12-13 00:00:00', '2025-12-14 00:00:00', '2025-12-15 00:00:00', '2025-12-16 00:00:00', '2025-12-17 00:00:00', '2025-12-18 00:00:00']
After excluding specific brands for PANAM - current count: (36920)
Applied special SKU days cover to 244 rows for store PANAM

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')

Merging with suppliers (override)...
Found 26261 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.01s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.06s
  - Location: PANAM
  - Rows processed: 36920
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10659 rows
  - No supplier data: 26261 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/5. Miss Glam Panam.csv

Processing PO file: 6. Miss Glam Muaro Bungo.csv ....
  - Extracted location: MUARO BUNGO
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8998824552817', '8993137708319', '10500637314', '8809623612735', '10300514242']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Muaro Bungo']
  [DEBUG] _build_stock_top100_map: Using date column '2025-12-22 00:00:00' for running_date '22 Dec 2025'
  [DEBUG] _build_stock_top100_map: Found fallback column '2025-12-21 00:00:00' for day before
  [DEBUG] Stock source breakdown: 0 from target date, 0 from day before, 100 will use original stock
  [DEBUG] _build_stock_top100_map: Built map with 100 SKU+toko_key combinations
  [DEBUG] Merging top_stock_map on ['SKU', 'toko_key']
  [DEBUG] Merge matched 0 rows with Top 100 stock data
  [DEBUG] 0 Top 100 SKUs have different stock_top100 values
After excluding specific brands for MUARO BUNGO - current count: (36883)

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)

Applied special SKU days cover to 238 rows for store MUARO BUNGO
Merging with suppliers (override)...
Found 26413 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.02s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.07s
  - Location: MUARO BUNGO
  - Rows processed: 36883
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10470 rows
  - No supplier data: 26413 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/6. Miss Glam Muaro Bungo.csv

Processing PO file: 7. Miss Glam Lampung.csv ....
  - Extracted location: LAMPUNG
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['30200186137', '8997225412300', '8993137718936', '8991038775171', '8992821101306']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Lampung']
  [DEBUG] _build_stock_top100_map: Using date column '2025-12-22 00:00:00' for running_date '22 Dec 2025'
  [DEBUG] _build_stock_top100_map: Found fallback column '2025-12-21 00:00:00' for day before
  [DEBUG] Stock source breakdown: 0 from target date, 0 from day before, 100 will use original stock
  [DEBUG] _build_stock_top100_map: Built map with 100 SKU+toko_key combinations
  [DEBUG] Merging top_stock_map on ['SKU', 'toko_key']
  [DEBUG] Merge matched 0 rows with Top 100 stock data
  [DEBUG] 0 Top 100 SKUs have different stock_top100 values
After excluding specific brands for LAMPUNG - current count: (36794)

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)

Applied special SKU days cover to 249 rows for store LAMPUNG
Merging with suppliers (override)...
Found 26301 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.01s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.06s
  - Location: LAMPUNG
  - Rows processed: 36794
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10493 rows
  - No supplier data: 26301 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/7. Miss Glam Lampung.csv

Processing PO file: 8. Miss Glam Bengkulu.csv ....
  - Extracted location: BENGKULU
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['10400618143', '30400260030', '10300514242', '8993137718936', '8991038775171']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Bengkulu']
  [DEBUG] _build_stock_top100_map: Using date column '2025-12-22 00:00:00' for running_date '22 Dec 2025'
  [DEBUG] _build_stock_top100_map: Found fallback column '2025-12-21 00:00:00' for day before
  [DEBUG] Stock source breakdown: 0 from target date, 0 from day before, 100 will use original stock
  [DEBUG] _build_stock_top100_map: Built map with 100 SKU+toko_key combinations
  [DEBUG] Merging top_stock_map on ['SKU', 'toko_key']
  [DEBUG] Merge matched 0 rows with Top 100 stock data
  [DEBUG] 0 Top 100 SKUs have different stock_top100 values
After excluding specific brands for BENGKULU - current count: (36735)

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)
/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1400292012.py:45: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s = s.replace(list(NA_VALUES), np.nan)

Applied special SKU days cover to 248 rows for store BENGKULU
Merging with suppliers (override)...
Found 26366 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.01s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.06s
  - Location: BENGKULU
  - Rows processed: 36735
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10369 rows
  - No supplier data: 26366 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/8. Miss Glam Bengkulu.csv

Processing PO file: 9. Miss Glam Medan.csv ....
  - Extracted location: MEDAN
  [DEBUG] top_sku_col: SKU, clean_sku_col: SKU
  [DEBUG] Found 100 Top 100 SKUs
  [DEBUG] Sample Top 100 SKUs: ['8993137708319', '20100493603', '10300514242', '8993137718936', '8998824553340']
  [DEBUG] Marked 100 rows as Top 100 SKUs in df_clean
  [DEBUG] Initialized stock_top100 with base stock column 'Stok'
  [DEBUG] df_clean has 'Toko' column: True
  [DEBUG] Sample Toko values in df_clean: ['Miss Glam Medan']
  [DEBUG] _build_stock_top100_map: No date column matched for '22 Dec 2025'
  [DEBUG] Available columns: ['No.', 'Brand', 'SKU', 'Nama', 'Toko', 'Produk ada atau tidak (di grosir terdekat & tercepat)', '2025-12-09 00:00:00', '2025-12-10 00:00:00', '2025-12-11 00:00:00', '2025-12-12 00:00:00', '2025-12-13 00:00:00', '2025-12-14 00:00:00', '2025-12-15 00:00:00', '2025-12-16 00:00:00', '2025-12-17 00:00:00', '2025-12-18 00:00:00']
After excluding specific brands for MEDAN - current count: (37022)
Applied special SKU days cover to 248 rows for store MEDAN

/var/folders/8t/7219xcjd2dj829bf02_x9zy80000gn/T/ipykernel_9809/1251970027.py:60: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  col_ts = pd.to_datetime(normalized_col, dayfirst=True, errors='coerce')

Merging with suppliers (override)...
Found 26341 rows without store match; attempting brand-only fallback for non-empty brands...
[TIMING] suppliers: prep=0.02s primary_merge=0.01s fallback_merge=0.01s apply_fallback=0.02s fillna=0.01s total=0.06s
  - Location: MEDAN
  - Rows processed: 37022
  - 'Miss Glam Padang' suppliers: 0 rows
  - Other suppliers: 10681 rows
  - No supplier data: 26341 rows
  - Scheduled saves for: /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/9. Miss Glam Medan.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/12. Miss Glam Bangka.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/11. Miss Glam Damar.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/12. Miss Glam Bangka.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/12. Miss Glam Bangka.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/12. Miss Glam Bangka.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/11. Miss Glam Damar.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/11. Miss Glam Damar.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/11. Miss Glam Damar.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/13. Miss Glam Payakumbuh.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/14. Miss Glam Solok.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/14. Miss Glam Solok.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/14. Miss Glam Solok.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/14. Miss Glam Solok.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/13. Miss Glam Payakumbuh.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/13. Miss Glam Payakumbuh.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/13. Miss Glam Payakumbuh.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/15. Miss Glam Tembilahan.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/16. Miss Glam Lubuk Linggau.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/15. Miss Glam Tembilahan.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/15. Miss Glam Tembilahan.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/15. Miss Glam Tembilahan.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/16. Miss Glam Lubuk Linggau.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/16. Miss Glam Lubuk Linggau.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/16. Miss Glam Lubuk Linggau.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/17. Miss Glam Dumai.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/18. Miss Glam Kedaton.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/17. Miss Glam Dumai.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/17. Miss Glam Dumai.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/17. Miss Glam Dumai.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/18. Miss Glam Kedaton.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/18. Miss Glam Kedaton.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/18. Miss Glam Kedaton.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/19. Miss Glam Rantau Prapat.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/2. Miss Glam Pekanbaru.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/19. Miss Glam Rantau Prapat.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/19. Miss Glam Rantau Prapat.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/19. Miss Glam Rantau Prapat.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/2. Miss Glam Pekanbaru.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/2. Miss Glam Pekanbaru.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/2. Miss Glam Pekanbaru.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/20. Miss Glam Tanjung Pinang.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/21. Miss Glam Sutomo.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/20. Miss Glam Tanjung Pinang.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/21. Miss Glam Sutomo.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/20. Miss Glam Tanjung Pinang.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/21. Miss Glam Sutomo.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/20. Miss Glam Tanjung Pinang.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/21. Miss Glam Sutomo.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/23. Miss Glam Halat.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/22. Miss Glam Pasaman Barat.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/23. Miss Glam Halat.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/23. Miss Glam Halat.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/23. Miss Glam Halat.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/22. Miss Glam Pasaman Barat.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/22. Miss Glam Pasaman Barat.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/22. Miss Glam Pasaman Barat.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/24. Miss Glam Duri.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/25. Miss Glam Sudirman.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/24. Miss Glam Duri.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/24. Miss Glam Duri.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/24. Miss Glam Duri.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/25. Miss Glam Sudirman.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/25. Miss Glam Sudirman.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/25. Miss Glam Sudirman.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/27. Miss Glam P. Sidimpuan.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/26. Miss Glam Dr. Mansyur.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/27. Miss Glam P. Sidimpuan.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/27. Miss Glam P. Sidimpuan.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/27. Miss Glam P. Sidimpuan.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/26. Miss Glam Dr. Mansyur.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/26. Miss Glam Dr. Mansyur.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/26. Miss Glam Dr. Mansyur.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/28. Miss Glam Aceh.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/29. Miss Glam Marpoyan.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/28. Miss Glam Aceh.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/28. Miss Glam Aceh.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/28. Miss Glam Aceh.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/29. Miss Glam Marpoyan.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/29. Miss Glam Marpoyan.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/29. Miss Glam Marpoyan.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/30. Miss Glam Sei Penuh.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/3. Miss Glam Jambi.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/30. Miss Glam Sei Penuh.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/3. Miss Glam Jambi.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/30. Miss Glam Sei Penuh.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/30. Miss Glam Sei Penuh.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/3. Miss Glam Jambi.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/3. Miss Glam Jambi.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/31. Miss Glam Mayang.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/32. Miss Glam Soeta.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/32. Miss Glam Soeta.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/31. Miss Glam Mayang.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/32. Miss Glam Soeta.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/32. Miss Glam Soeta.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/31. Miss Glam Mayang.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/31. Miss Glam Mayang.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/33. Miss Glam Balikpapan.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/34. Miss Glam Pematang Siantar.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/33. Miss Glam Balikpapan.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/33. Miss Glam Balikpapan.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/33. Miss Glam Balikpapan.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/34. Miss Glam Pematang Siantar.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/34. Miss Glam Pematang Siantar.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/34. Miss Glam Pematang Siantar.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/35. Miss Glam Batoh.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/4. Miss Glam Bukittinggi.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/35. Miss Glam Batoh.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/35. Miss Glam Batoh.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/35. Miss Glam Batoh.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/4. Miss Glam Bukittinggi.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/4. Miss Glam Bukittinggi.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/4. Miss Glam Bukittinggi.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/6. Miss Glam Muaro Bungo.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/5. Miss Glam Panam.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/5. Miss Glam Panam.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/6. Miss Glam Muaro Bungo.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/5. Miss Glam Panam.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/6. Miss Glam Muaro Bungo.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/5. Miss Glam Panam.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/6. Miss Glam Muaro Bungo.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/8. Miss Glam Bengkulu.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/7. Miss Glam Lampung.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/8. Miss Glam Bengkulu.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/8. Miss Glam Bengkulu.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/8. Miss Glam Bengkulu.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/7. Miss Glam Lampung.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/7. Miss Glam Lampung.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/7. Miss Glam Lampung.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/xlsx/9. Miss Glam Medan.xlsx
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/complete/csv/9. Miss Glam Medan.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/m2/9. Miss Glam Medan.csv
File saved to /Users/andresuchitra/dev/missglam/autopo/notebook/output/20251222/emergency/9. Miss Glam Medan.csv

Processing complete! Summary:

,file,location,total_rows,padang_suppliers,other_suppliers,no_supplier,status,output_path
0,1. Miss Glam Padang.csv,PADANG,37278,11114,0,26164,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
1,10. Miss Glam Palembang.csv,PALEMBANG,36856,0,10495,26361,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
2,11. Miss Glam Damar.csv,DAMAR,37472,0,11135,26337,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
3,12. Miss Glam Bangka.csv,BANGKA,36826,0,10400,26426,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
4,13. Miss Glam Payakumbuh.csv,PAYAKUMBUH,36917,0,10699,26218,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
5,14. Miss Glam Solok.csv,SOLOK,36905,0,10701,26204,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
6,15. Miss Glam Tembilahan.csv,TEMBILAHAN,36779,0,10506,26273,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
7,16. Miss Glam Lubuk Linggau.csv,LUBUK LINGGAU,36799,0,10130,26669,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
8,17. Miss Glam Dumai.csv,DUMAI,36887,0,10628,26259,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
9,18. Miss Glam Kedaton.csv,KEDATON,36847,0,10459,26388,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
10,19. Miss Glam Rantau Prapat.csv,RANTAU PRAPAT,36785,0,10443,26342,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
11,2. Miss Glam Pekanbaru.csv,PEKANBARU,37108,0,10835,26273,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
12,20. Miss Glam Tanjung Pinang.csv,TANJUNG PINANG,36717,0,10313,26404,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
13,21. Miss Glam Sutomo.csv,SUTOMO,37131,0,10874,26257,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
14,22. Miss Glam Pasaman Barat.csv,PASAMAN BARAT,36782,0,10565,26217,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
15,23. Miss Glam Halat.csv,HALAT,36899,0,10974,25925,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
16,24. Miss Glam Duri.csv,DURI,36836,0,10585,26251,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
17,25. Miss Glam Sudirman.csv,SUDIRMAN,37210,0,10834,26376,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
18,26. Miss Glam Dr. Mansyur.csv,DR. MANSYUR,36873,0,10913,25960,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
19,27. Miss Glam P. Sidimpuan.csv,P. SIDIMPUAN,36813,0,10370,26443,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
20,28. Miss Glam Aceh.csv,ACEH,36742,0,10227,26515,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
21,29. Miss Glam Marpoyan.csv,MARPOYAN,36905,0,10528,26377,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
22,3. Miss Glam Jambi.csv,JAMBI,36943,0,10575,26368,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
23,30. Miss Glam Sei Penuh.csv,SEI PENUH,36809,0,10287,26522,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
24,31. Miss Glam Mayang.csv,MAYANG,36816,0,9990,26826,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
25,32. Miss Glam Soeta.csv,SOETA,37303,0,6481,30822,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
26,33. Miss Glam Balikpapan.csv,BALIKPAPAN,37081,0,6674,30407,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
27,34. Miss Glam Pematang Siantar.csv,PEMATANG SIANTAR,37763,0,0,37763,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
28,35. Miss Glam Batoh.csv,BATOH,37749,0,0,37749,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
29,4. Miss Glam Bukittinggi.csv,BUKITTINGGI,36915,0,10726,26189,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
30,5. Miss Glam Panam.csv,PANAM,36920,0,10659,26261,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
31,6. Miss Glam Muaro Bungo.csv,MUARO BUNGO,36883,0,10470,26413,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
32,7. Miss Glam Lampung.csv,LAMPUNG,36794,0,10493,26301,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
33,8. Miss Glam Bengkulu.csv,BENGKULU,36735,0,10369,26366,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...
34,9. Miss Glam Medan.csv,MEDAN,37022,0,10681,26341,Success,/Users/andresuchitra/dev/missglam/autopo/noteb...

Sample of the last processed file:

,Brand,Kategori Brand,SKU,Nama,Toko,Stok,Daily Sales,Max. Daily Sales,Lead Time,Max. Lead Time,...,Nama Supplier,ID Brand,Nama Brand,ID Store,Nama Store,Hari Order,Min. Purchase,Trading Term,Promo Factor,Delay Factor
0,nan,0,10100606447,BANILA CO Clean It Zero Tea Tree EX Pore Clar...,Miss Glam Medan,0.00,0.00,0.00,0.00,0.00,...,,0.00,NaN,0.00,,0.00,0.00,0.00,,
1,nan,0,50900308407,ACCESORIES Tempat Soflent 94025,Miss Glam Medan,3.00,0.00,0.00,0.00,0.00,...,,0.00,NaN,0.00,,0.00,0.00,0.00,,
2,nan,0,50800468850,ACCESSORIES Bando BL 90,Miss Glam Medan,0.00,0.00,0.00,0.00,0.00,...,,0.00,NaN,0.00,,0.00,0.00,0.00,,
3,nan,0,51300243348,"ACCESSORIES Gantungan Kunci GT YSK 3272, 3320,...",Miss Glam Medan,17.00,0.25,2.00,1.00,2.00,...,,0.00,NaN,0.00,,0.00,0.00,0.00,,
4,nan,0,50700632008,ACCESSORIES Kaca 155 CD,Miss Glam Medan,0.00,0.00,0.00,0.00,0.00,...,,0.00,NaN,0.00,,0.00,0.00,0.00,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37017,ZYWELL,DELISTING,10500322936,ZYWELL Pell Off Mask Cellendula 10g,Miss Glam Medan,0.00,0.00,0.00,0.00,0.00,...,,0.00,NaN,0.00,,0.00,0.00,0.00,,
37018,ZYWELL,DELISTING,18200200793,ZYWELL Pell Off Mask CHamomille 10g,Miss Glam Medan,0.00,0.00,0.00,0.00,0.00,...,,0.00,NaN,0.00,,0.00,0.00,0.00,,
37019,ZYWELL,DELISTING,10500300101,ZYWELL Pell Off Mask Jasmine 10g,Miss Glam Medan,0.00,0.00,0.00,0.00,0.00,...,,0.00,NaN,0.00,,0.00,0.00,0.00,,
37020,ZYWELL,DELISTING,10500322858,ZYWELL Pell Off Mask Rose 10g,Miss Glam Medan,0.00,0.00,0.00,0.00,0.00,...,,0.00,NaN,0.00,,0.00,0.00,0.00,,
37021,ZYWELL,DELISTING,10500322711,ZYWELL Pell Off Mask Saffron10g,Miss Glam Medan,0.00,0.00,0.00,0.00,0.00,...,,0.00,NaN,0.00,,0.00,0.00,0.00,,